import { useEffect, useMemo, useRef, useState } from 'react';
import JSZip from 'jszip';
import { downloadBytes, downloadText } from '../../lib/download';
import { collectRequiredCodePoints, inspectFont, subsetToWoff2, type FontInspection, type FontPreset, type FontSubsetResult } from './font-engine';
import { consumeFileInput } from '../../lib/file-input';

const PRESET_OPTIONS:Array<{id:FontPreset;label:string}>=[{id:'basic-latin',label:'Basic Latin'},{id:'latin-1',label:'Latin-1 supplement'},{id:'digits',label:'Digits'},{id:'punctuation',label:'Punctuation'}];
const GLYPH_PAGE_SIZE=200;
function formatBytes(value:number){if(value<1024)return`${value} B`;if(value<1024*1024)return`${(value/1024).toFixed(1)} KiB`;return`${(value/1024/1024).toFixed(2)} MiB`;}
function cssFor(result:FontSubsetResult,fileName:string){const family=`${result.familyName} Subset`.replace(/'/g,"\\'");return`@font-face {\n  font-family: '${family}';\n  src: url('./${fileName}') format('woff2');\n  font-style: ${result.cssStyle};\n  font-weight: ${result.weight};\n  font-display: swap;\n  unicode-range: ${result.unicodeRange};\n}\n`;}

export default function FontWorkspace(){
 const sourceFaceRef=useRef<FontFace|null>(null),subsetFaceRef=useRef<FontFace|null>(null);const [sourceFamily,setSourceFamily]=useState('sans-serif'),[subsetFamily,setSubsetFamily]=useState('sans-serif');const [file,setFile]=useState<File|null>(null),[buffer,setBuffer]=useState<ArrayBuffer|null>(null),[inspection,setInspection]=useState<FontInspection|null>(null),[presets,setPresets]=useState<FontPreset[]>(['basic-latin']),[customText,setCustomText]=useState(''),[previewText,setPreviewText]=useState('Hamburgefontsiv 0123456789'),[query,setQuery]=useState(''),[page,setPage]=useState(0),[subset,setSubset]=useState<FontSubsetResult|null>(null),[busy,setBusy]=useState(false),[status,setStatus]=useState('Choose a TTF, OTF, WOFF, or WOFF2 font to inspect it locally.');
 useEffect(()=>()=>{if(sourceFaceRef.current)document.fonts.delete(sourceFaceRef.current);if(subsetFaceRef.current)document.fonts.delete(subsetFaceRef.current);},[]);
 const requested=useMemo(()=>collectRequiredCodePoints({presets,customText}),[customText,presets]);
 const matchingGlyphs=useMemo(()=>{if(!inspection)return[];const needle=query.trim().toLowerCase();if(!needle)return inspection.glyphs;return inspection.glyphs.filter((glyph)=>glyph.name.toLowerCase().includes(needle)||glyph.character.includes(query)||`u+${glyph.codePoint.toString(16).padStart(4,'0')}`.includes(needle));},[inspection,query]);
 const pageCount=Math.max(1,Math.ceil(matchingGlyphs.length/GLYPH_PAGE_SIZE)),visibleGlyphs=matchingGlyphs.slice(page*GLYPH_PAGE_SIZE,(page+1)*GLYPH_PAGE_SIZE);
 useEffect(()=>setPage(0),[query,inspection]);
 async function loadFace(bytes:BufferSource,family:string,descriptors:FontFaceDescriptors,which:'source'|'subset'){if(typeof FontFace==='undefined')return;const ref=which==='source'?sourceFaceRef:subsetFaceRef;if(ref.current)document.fonts.delete(ref.current);const face=new FontFace(family,bytes,descriptors);await face.load();document.fonts.add(face);ref.current=face;if(which==='source')setSourceFamily(family);else setSubsetFamily(family);}
 async function chooseFile(next:File|undefined){if(!next)return;setBusy(true);setFile(next);setInspection(null);setSubset(null);setStatus('Parsing font tables and cmap locally…');try{const bytes=await next.arrayBuffer(),result=await inspectFont(bytes,next.name);setBuffer(bytes);setInspection(result);try{await loadFace(bytes,`InmoSource-${Date.now()}`,{style:result.cssStyle,weight:String(result.weight)},'source');}catch{setSourceFamily('sans-serif');}setStatus(`Parsed ${result.glyphCount.toLocaleString()} glyphs and ${result.glyphs.length.toLocaleString()} cmap mappings. ${result.safeToSubset?'This font has no detected layout/variation tables that this reconstruction path would discard.':`Safe subsetting blocked: ${result.unsupportedFeatures.join(', ')}.`}`);}catch(error){setBuffer(null);setStatus(`Font inspection failed: ${error instanceof Error?error.message:'unsupported font'}`);}finally{setBusy(false);}}
 function invalidate(){setSubset(null);if(subsetFaceRef.current){document.fonts.delete(subsetFaceRef.current);subsetFaceRef.current=null;}setSubsetFamily('sans-serif');}
 function togglePreset(preset:FontPreset){setPresets((current)=>current.includes(preset)?current.filter((value)=>value!==preset):[...current,preset]);invalidate();}
 async function buildSubset(){if(!buffer||!inspection)return;setBusy(true);setStatus('Building a WOFF2 subset locally…');try{const result=await subsetToWoff2(buffer,{presets,customText});setSubset(result);try{await loadFace(result.bytes.slice().buffer as ArrayBuffer,`InmoSubset-${Date.now()}`,{style:result.cssStyle,weight:String(result.weight),unicodeRange:result.unicodeRange},'subset');}catch{setSubsetFamily('sans-serif');}setStatus(`Subset ready: ${result.glyphCount.toLocaleString()} glyphs · ${formatBytes(result.bytes.byteLength)}. ${result.missingCodePoints.length?`${result.missingCodePoints.length} requested code point${result.missingCodePoints.length===1?' is':'s are'} absent from the source.`:'All requested code points were found.'}`);}catch(error){setStatus(`Subset blocked/failed: ${error instanceof Error?error.message:'font encoding error'}`);}finally{setBusy(false);}}
 const outputBase=file?.name.replace(/\.[^.]+$/,'')||'font',woffName=`${outputBase}.subset.woff2`,css=subset?cssFor(subset,woffName):'';
 async function downloadBundle(){if(!subset)return;const zip=new JSZip();zip.file(woffName,subset.bytes);zip.file(`${outputBase}.subset.css`,css);downloadBytes(new Uint8Array(await zip.generateAsync({type:'uint8array'})),`${outputBase}.subset.zip`,'application/zip');setStatus('Downloaded WOFF2 + CSS bundle.');}
 return <><div className="workspace-header"><div><h2>Font glyph subsetter</h2><p>Inspect cmap and OpenType feature dependencies, then subset only when this local reconstruction path can do so without silently discarding detected layout features.</p></div></div><div className="workspace-body"><div className="field"><label htmlFor="font-file">Font file</label><input id="font-file" type="file" accept=".ttf,.otf,.woff,.woff2,font/ttf,font/otf,font/woff,font/woff2" onChange={(event)=>consumeFileInput(event.target,()=>chooseFile(event.target.files?.[0]))}/></div>
 {inspection?<><div className="metric-row"><div className="metric"><span>Family</span><strong>{inspection.familyName}</strong></div><div className="metric"><span>Style</span><strong>{inspection.styleName}</strong></div><div className="metric"><span>Weight</span><strong>{inspection.weight}</strong></div><div className="metric"><span>Glyphs</span><strong>{inspection.glyphCount.toLocaleString()}</strong></div><div className="metric"><span>Source</span><strong>{formatBytes(inspection.inputBytes)}</strong></div></div>
 {!inspection.safeToSubset?<div className="notice" style={{marginTop:16}}><strong>Safe subset blocked.</strong> This font contains {inspection.unsupportedFeatures.join(', ')}. OpenType Layout tables control substitution/positioning; rebuilding outlines without those tables can change text shaping, so this tool will not emit a degraded subset. The source preview and coverage inspector remain available.</div>:<div className="notice" style={{marginTop:16}}>No detected GSUB/GPOS/GDEF, variation, color-glyph, AAT, or other blocked layout tables. The simple-font reconstruction path is available.</div>}
 <details style={{marginTop:14}}><summary>Detected font tables</summary><p style={{overflowWrap:'anywhere'}}>{inspection.tableTags.join(', ')||'No table tags reported.'}</p></details>
 <div className="field" style={{marginTop:18}}><label htmlFor="font-preview-text">Preview text</label><textarea id="font-preview-text" value={previewText} onChange={(event)=>setPreviewText(event.target.value)}/></div><div className="workspace-grid"><div className="notice"><strong>Source font</strong><div style={{fontFamily:`'${sourceFamily}', sans-serif`,fontStyle:inspection.cssStyle,fontWeight:inspection.weight,fontSize:28,lineHeight:1.4,overflowWrap:'anywhere'}}>{previewText||' '}</div></div><div className="notice"><strong>Generated subset</strong><div style={{fontFamily:subset?`'${subsetFamily}', sans-serif`:'sans-serif',fontStyle:inspection.cssStyle,fontWeight:inspection.weight,fontSize:28,lineHeight:1.4,overflowWrap:'anywhere'}}>{subset?previewText:'Build a subset to compare the actual generated WOFF2.'}</div></div></div>
 <div className="workspace-grid" style={{marginTop:20}}><div><span className="field-label">Unicode presets</span><div className="check-list">{PRESET_OPTIONS.map((option)=><label className="check-item" key={option.id}><input type="checkbox" checked={presets.includes(option.id)} onChange={()=>togglePreset(option.id)}/><span>{option.label}</span></label>)}</div></div><div className="field"><label htmlFor="font-custom">Custom characters / sample text</label><textarea id="font-custom" value={customText} onChange={(event)=>{setCustomText(event.target.value);invalidate();}}/><small>{requested.length.toLocaleString()} unique requested code points.</small></div></div>
 <div className="button-row"><button className="action-button" type="button" disabled={busy||requested.length===0||!inspection.safeToSubset} onClick={()=>void buildSubset()}>{busy?'Working locally…':'Build WOFF2 subset'}</button>{subset?<><button className="action-button secondary" type="button" onClick={()=>downloadBytes(subset.bytes,woffName,'font/woff2')}>Download WOFF2</button><button className="action-button secondary" type="button" onClick={()=>downloadText(css,`${outputBase}.subset.css`,'text/css;charset=utf-8')}>Download CSS</button><button className="action-button secondary" type="button" onClick={()=>void downloadBundle()}>Download WOFF2 + CSS ZIP</button></>:null}</div>
 {subset?<div className="workspace-grid" style={{marginTop:18}}><div className="notice"><strong>Subset result</strong><br/>{subset.glyphCount.toLocaleString()} glyphs · {formatBytes(subset.bytes.byteLength)}<br/><strong>Missing requested code points:</strong> {subset.missingCodePoints.length?subset.missingCodePoints.map((point)=>`U+${point.toString(16).toUpperCase()}`).join(', '):'none'}<br/><strong>Unicode range:</strong> <span style={{overflowWrap:'anywhere'}}>{subset.unicodeRange}</span></div><div className="field"><label htmlFor="font-css">@font-face snippet</label><textarea id="font-css" readOnly value={css}/></div></div>:null}
 <h3 style={{marginTop:24}}>Glyph coverage</h3><div className="field"><label htmlFor="glyph-search">Search glyphs</label><input id="glyph-search" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Character, glyph name, or U+0041"/><small>{matchingGlyphs.length.toLocaleString()} matching cmap mappings; {visibleGlyphs.length.toLocaleString()} shown on this page.</small></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill, minmax(110px, 1fr))',gap:8,marginTop:14}} role="list" aria-label="Font glyph coverage">{visibleGlyphs.map((glyph)=><div role="listitem" key={`${glyph.codePoint}-${glyph.glyphIndex}`} style={{border:'1px solid var(--line)',borderRadius:'var(--radius-sm)',padding:10,minWidth:0}}><div aria-hidden="true" style={{fontFamily:`'${sourceFamily}', sans-serif`,fontSize:30,lineHeight:1.2,overflow:'hidden'}}>{glyph.character}</div><strong style={{display:'block',overflowWrap:'anywhere'}}>{glyph.name}</strong><small>U+{glyph.codePoint.toString(16).toUpperCase().padStart(4,'0')} · aw {glyph.advanceWidth}</small></div>)}</div>{pageCount>1?<div className="button-row" role="group" aria-label="Glyph pages"><button className="action-button secondary" type="button" disabled={page===0} onClick={()=>setPage((value)=>Math.max(0,value-1))}>Previous glyphs</button><span>Page {page+1} of {pageCount}</span><button className="action-button secondary" type="button" disabled={page>=pageCount-1} onClick={()=>setPage((value)=>Math.min(pageCount-1,value+1))}>Next glyphs</button></div>:null}
 </>:null}<div className={`status-line ${inspection?'good':''}`} role="status">{status}</div></div></>;
}
