// Curated static reference datasets used for fully offline, deterministic
// lexical forensics. These are intentionally small, hand-verified lists (not a
// live fetch of a third-party ranking service) so Group 1 features work with
// zero network access and zero external CORS dependency.

/** High-value global brand domains most frequently impersonated by typosquatters. */
export const BRAND_REFERENCE_DOMAINS: string[] = [
  'google.com', 'youtube.com', 'facebook.com', 'instagram.com', 'whatsapp.com',
  'amazon.com', 'apple.com', 'microsoft.com', 'live.com', 'office.com',
  'paypal.com', 'netflix.com', 'linkedin.com', 'twitter.com', 'x.com',
  'wikipedia.org', 'yahoo.com', 'reddit.com', 'ebay.com', 'bing.com',
  'github.com', 'gitlab.com', 'stackoverflow.com', 'dropbox.com', 'adobe.com',
  'chase.com', 'bankofamerica.com', 'wellsfargo.com', 'citibank.com', 'capitalone.com',
  'americanexpress.com', 'coinbase.com', 'binance.com', 'stripe.com', 'shopify.com',
  'walmart.com', 'target.com', 'bestbuy.com', 'costco.com', 'homedepot.com',
  'zoom.us', 'slack.com', 'discord.com', 'spotify.com', 'tiktok.com',
  'pinterest.com', 'snapchat.com', 'twitch.tv', 'salesforce.com', 'oracle.com',
  'ibm.com', 'intel.com', 'samsung.com', 'sony.com', 'nvidia.com',
  'cloudflare.com', 'godaddy.com', 'namecheap.com', 'digitalocean.com', 'aws.amazon.com',
  'icloud.com', 'gmail.com', 'outlook.com', 'protonmail.com', 'usps.com',
  'fedex.com', 'ups.com', 'dhl.com', 'irs.gov', 'ssa.gov',
  'steam.com', 'steampowered.com', 'epicgames.com', 'ea.com', 'roblox.com',
  'airbnb.com', 'booking.com', 'expedia.com', 'uber.com', 'lyft.com',
  'doordash.com', 'grubhub.com', 'venmo.com', 'zelle.com', 'wise.com',
  'binance.us', 'kraken.com', 'robinhood.com', 'fidelity.com', 'vanguard.com',
  'schwab.com', 'etrade.com', 'hsbc.com', 'barclays.co.uk', 'santander.com',
  'att.com', 'verizon.com', 't-mobile.com', 'comcast.com', 'xfinity.com',
];

/** Multi-label public-suffix-style TLDs handled explicitly for registrable-domain splitting. */
export const MULTI_PART_TLDS: Set<string> = new Set([
  'co.uk', 'org.uk', 'gov.uk', 'ac.uk', 'me.uk', 'ltd.uk', 'plc.uk', 'net.uk', 'sch.uk',
  'co.jp', 'or.jp', 'ne.jp', 'ac.jp', 'go.jp',
  'co.nz', 'org.nz', 'govt.nz', 'ac.nz', 'net.nz',
  'com.au', 'net.au', 'org.au', 'edu.au', 'gov.au', 'id.au',
  'co.in', 'net.in', 'org.in', 'gen.in', 'firm.in', 'ind.in',
  'com.br', 'net.br', 'org.br', 'gov.br',
  'com.cn', 'net.cn', 'org.cn', 'gov.cn',
  'co.za', 'org.za', 'net.za', 'gov.za',
  'com.mx', 'org.mx', 'net.mx', 'gob.mx',
  'com.ar', 'net.ar', 'org.ar', 'gob.ar',
  'co.kr', 'or.kr', 'ne.kr', 'go.kr',
  'com.sg', 'org.sg', 'net.sg', 'gov.sg', 'edu.sg',
  'com.hk', 'org.hk', 'net.hk', 'gov.hk', 'edu.hk',
  'co.id', 'or.id', 'go.id', 'ac.id',
  'com.tr', 'org.tr', 'net.tr', 'gov.tr',
  'co.il', 'org.il', 'net.il', 'gov.il', 'ac.il',
  'com.tw', 'org.tw', 'net.tw', 'gov.tw', 'edu.tw',
  'github.io', 'pages.dev', 'vercel.app', 'netlify.app', 'web.app',
]);

/** Known URL-shortener / vanity-link hosts. Not exhaustive; extend as new services are verified. */
export const KNOWN_SHORTENERS: Record<string, string> = {
  'bit.ly': 'Bitly',
  'tinyurl.com': 'TinyURL',
  't.co': 'X (Twitter) Link Shortener',
  'goo.gl': 'Google URL Shortener (retired)',
  'ow.ly': 'Hootsuite Ow.ly',
  'is.gd': 'is.gd',
  'buff.ly': 'Buffer',
  'rebrand.ly': 'Rebrandly',
  'shorturl.at': 'ShortURL',
  't.ly': 'T.LY',
  'cutt.ly': 'Cuttly',
  'rb.gy': 'Rebrandly (rb.gy)',
  'shorte.st': 'Shorte.st',
  'v.gd': 'v.gd',
  'tiny.cc': 'Tiny.cc',
  's.id': 's.id',
  'lnkd.in': 'LinkedIn Shortener',
  'fb.me': 'Facebook Shortener',
  'amzn.to': 'Amazon Shortener',
  'youtu.be': 'YouTube Shortener',
  'bl.ink': 'BL.INK',
  'clck.ru': 'Yandex Clck.ru',
  'qlink.me': 'Qlink',
  'shorturl.com': 'ShortURL.com',
  'x.co': 'GoDaddy X.co',
};

/** Query keys that identify cross-site tracking, analytics, or ad-attribution payloads. */
export const TRACKING_PARAM_PATTERNS: Array<{ pattern: RegExp; service: string }> = [
  { pattern: /^utm_/i, service: 'Google Analytics Campaign (UTM)' },
  { pattern: /^fbclid$/i, service: 'Meta/Facebook Click ID' },
  { pattern: /^gclid$/i, service: 'Google Ads Click ID' },
  { pattern: /^gclsrc$/i, service: 'Google Ads Click Source' },
  { pattern: /^dclid$/i, service: 'Google Marketing Platform Click ID' },
  { pattern: /^msclkid$/i, service: 'Microsoft Ads Click ID' },
  { pattern: /^mc_eid$/i, service: 'Mailchimp Email ID' },
  { pattern: /^mc_cid$/i, service: 'Mailchimp Campaign ID' },
  { pattern: /^_hsenc$/i, service: 'HubSpot Encoded Tracking' },
  { pattern: /^_hsmi$/i, service: 'HubSpot Message ID' },
  { pattern: /^igshid$/i, service: 'Instagram Share ID' },
  { pattern: /^ttclid$/i, service: 'TikTok Click ID' },
  { pattern: /^twclid$/i, service: 'X/Twitter Click ID' },
  { pattern: /^li_fat_id$/i, service: 'LinkedIn First-Party Ad Tracking ID' },
  { pattern: /^vero_id$/i, service: 'Vero Email Tracking' },
  { pattern: /^yclid$/i, service: 'Yandex Click ID' },
  { pattern: /^scid$/i, service: 'Snapchat Click ID' },
  { pattern: /^ref$/i, service: 'Generic Referral Tag' },
  { pattern: /^ref_src$/i, service: 'Referral Source Tag' },
  { pattern: /^spm$/i, service: 'Alibaba/Taobao Tracking' },
];

export const SESSION_PARAM_PATTERNS: RegExp[] = [
  /^sid$/i, /^sessionid$/i, /^session_id$/i, /^phpsessid$/i, /^jsessionid$/i, /^asp\.net_sessionid$/i, /^token$/i, /^auth$/i,
];

export const ROUTING_PARAM_PATTERNS: RegExp[] = [
  /^page$/i, /^p$/i, /^lang$/i, /^locale$/i, /^redirect(_to)?$/i, /^next$/i, /^returnurl$/i, /^view$/i, /^tab$/i, /^id$/i,
];

/** Small curated Unicode confusable map (Latin lookalikes) sufficient for common spoofing patterns. */
export const CONFUSABLE_MAP: Record<string, { looksLike: string; script: string }> = {
  '\u0430': { looksLike: 'a', script: 'Cyrillic' },
  '\u0435': { looksLike: 'e', script: 'Cyrillic' },
  '\u043E': { looksLike: 'o', script: 'Cyrillic' },
  '\u0440': { looksLike: 'p', script: 'Cyrillic' },
  '\u0441': { looksLike: 'c', script: 'Cyrillic' },
  '\u0443': { looksLike: 'y', script: 'Cyrillic' },
  '\u0445': { looksLike: 'x', script: 'Cyrillic' },
  '\u0456': { looksLike: 'i', script: 'Cyrillic' },
  '\u0458': { looksLike: 'j', script: 'Cyrillic' },
  '\u04BB': { looksLike: 'h', script: 'Cyrillic' },
  '\u051D': { looksLike: 'w', script: 'Cyrillic' },
  '\u0501': { looksLike: 'd', script: 'Cyrillic' },
  '\u0455': { looksLike: 's', script: 'Cyrillic' },
  '\u0399': { looksLike: 'I', script: 'Greek' },
  '\u03BF': { looksLike: 'o', script: 'Greek' },
  '\u03B1': { looksLike: 'a', script: 'Greek' },
  '\u03BD': { looksLike: 'v', script: 'Greek' },
  '\u03C1': { looksLike: 'p', script: 'Greek' },
  '\u0391': { looksLike: 'A', script: 'Greek' },
  '\u0392': { looksLike: 'B', script: 'Greek' },
  '\u0395': { looksLike: 'E', script: 'Greek' },
  '\u0397': { looksLike: 'H', script: 'Greek' },
  '\u041D': { looksLike: 'H', script: 'Cyrillic' },
  '\u0405': { looksLike: 'S', script: 'Cyrillic' },
  '\u0410': { looksLike: 'A', script: 'Cyrillic' },
  '\u0412': { looksLike: 'B', script: 'Cyrillic' },
  '\u0415': { looksLike: 'E', script: 'Cyrillic' },
  '\u041A': { looksLike: 'K', script: 'Cyrillic' },
  '\u041C': { looksLike: 'M', script: 'Cyrillic' },
  '\u041E': { looksLike: 'O', script: 'Cyrillic' },
  '\u0420': { looksLike: 'P', script: 'Cyrillic' },
  '\u0421': { looksLike: 'C', script: 'Cyrillic' },
  '\u0422': { looksLike: 'T', script: 'Cyrillic' },
  '\u0425': { looksLike: 'X', script: 'Cyrillic' },
  '0': { looksLike: 'O', script: 'Digit' },
  '1': { looksLike: 'l', script: 'Digit' },
};

/** DNSBL (DNS blackhole list) zones queryable via ordinary A-record DoH lookups. */
export const DNSBL_ZONES: Array<{ zone: string; label: string; kind: 'ip' | 'domain' }> = [
  { zone: 'zen.spamhaus.org', label: 'Spamhaus ZEN', kind: 'ip' },
  { zone: 'bl.spamcop.net', label: 'SpamCop Blocking List', kind: 'ip' },
  { zone: 'b.barracudacentral.org', label: 'Barracuda Reputation Block List', kind: 'ip' },
  { zone: 'dnsbl.sorbs.net', label: 'SORBS', kind: 'ip' },
  { zone: 'dbl.spamhaus.org', label: 'Spamhaus Domain Block List', kind: 'domain' },
  { zone: 'multi.surbl.org', label: 'SURBL Multi', kind: 'domain' },
];

/** CNAME/NS suffix signatures for deterministic CDN / hosting fingerprinting (Feature 29). */
export const CDN_SIGNATURES: Array<{ suffix: string; label: string }> = [
  { suffix: 'cloudflare.net', label: 'Cloudflare' },
  { suffix: 'cloudflare.com', label: 'Cloudflare' },
  { suffix: 'akamaiedge.net', label: 'Akamai' },
  { suffix: 'akamai.net', label: 'Akamai' },
  { suffix: 'akamaized.net', label: 'Akamai' },
  { suffix: 'edgekey.net', label: 'Akamai (EdgeKey)' },
  { suffix: 'edgesuite.net', label: 'Akamai (EdgeSuite)' },
  { suffix: 'fastly.net', label: 'Fastly' },
  { suffix: 'cloudfront.net', label: 'Amazon CloudFront' },
  { suffix: 'azureedge.net', label: 'Microsoft Azure CDN / Front Door' },
  { suffix: 'azurefd.net', label: 'Microsoft Azure Front Door' },
  { suffix: 'trafficmanager.net', label: 'Microsoft Azure Traffic Manager' },
  { suffix: 'cdn77.org', label: 'CDN77' },
  { suffix: 'stackpathdns.com', label: 'StackPath' },
  { suffix: 'stackpathcdn.com', label: 'StackPath' },
  { suffix: 'netdna-cdn.com', label: 'StackPath (legacy MaxCDN)' },
  { suffix: 'bunnycdn.com', label: 'BunnyCDN' },
  { suffix: 'b-cdn.net', label: 'BunnyCDN' },
  { suffix: 'gcore.lu', label: 'G-Core Labs' },
  { suffix: 'googleusercontent.com', label: 'Google Cloud / GGC' },
  { suffix: 'ghs.google.com', label: 'Google Hosted Service' },
  { suffix: 'shopify.com', label: 'Shopify' },
  { suffix: 'myshopify.com', label: 'Shopify' },
  { suffix: 'wpengine.com', label: 'WP Engine' },
  { suffix: 'herokuapp.com', label: 'Heroku' },
  { suffix: 'vercel-dns.com', label: 'Vercel' },
  { suffix: 'netlify.app', label: 'Netlify' },
  { suffix: 'github.io', label: 'GitHub Pages' },
  { suffix: 'pages.dev', label: 'Cloudflare Pages' },
  { suffix: 'sucuri.net', label: 'Sucuri WAF/CDN' },
  { suffix: 'incapdns.net', label: 'Imperva/Incapsula' },
];

/** URL path/asset-domain signatures for deterministic CMS/eCommerce fingerprinting (Feature 30). */
export const CMS_SIGNATURES: Array<{ pattern: RegExp; label: string }> = [
  { pattern: /\/wp-content\//i, label: 'WordPress' },
  { pattern: /\/wp-includes\//i, label: 'WordPress' },
  { pattern: /\/wp-json\//i, label: 'WordPress (REST API)' },
  { pattern: /cdn\.shopify\.com/i, label: 'Shopify' },
  { pattern: /\/cdn\/shop\//i, label: 'Shopify' },
  { pattern: /\.myshopify\.com/i, label: 'Shopify' },
  { pattern: /\/media\/wysiwyg\//i, label: 'Magento' },
  { pattern: /\/skin\/frontend\//i, label: 'Magento' },
  { pattern: /\/sites\/default\/files\//i, label: 'Drupal' },
  { pattern: /\/typo3(temp|conf)\//i, label: 'TYPO3' },
  { pattern: /\/squarespace-cdn\.com/i, label: 'Squarespace' },
  { pattern: /static1\.squarespace\.com/i, label: 'Squarespace' },
  { pattern: /\/webflow\.com/i, label: 'Webflow' },
  { pattern: /\.wixstatic\.com/i, label: 'Wix' },
  { pattern: /parastorage\.com/i, label: 'Wix' },
  { pattern: /\/ghost\/api\//i, label: 'Ghost' },
  { pattern: /\/_next\//i, label: 'Next.js' },
  { pattern: /\/_nuxt\//i, label: 'Nuxt.js' },
  { pattern: /\/umbraco\//i, label: 'Umbraco' },
  { pattern: /\/-\/media\//i, label: 'Sitecore' },
];
