import { readFile } from 'node:fs/promises';
import { expect, test, type Download } from '@playwright/test';

const inspectPngDownload = async (download: Download) => { const path = await download.path(); expect(path).not.toBeNull(); const bytes = await readFile(path!); expect([...bytes.subarray(0, 8)]).toEqual([137,80,78,71,13,10,26,10]); return { width: bytes.readUInt32BE(16), height: bytes.readUInt32BE(20) }; };
const inspectPdfDownload = async (download: Download) => { const path = await download.path(); expect(path).not.toBeNull(); const bytes = await readFile(path!); expect(bytes.subarray(0,5).toString('ascii')).toBe('%PDF-'); expect(bytes.byteLength).toBeGreaterThan(1_000); };

test.describe('Fiber Craft Workstation', () => {
  test('edits crochet charts, exports patterns, moves a portable project, and restores the local session', async ({ page }) => {
    await page.goto('./#/fiber-craft-workstation'); await expect(page.getByRole('heading', { name: 'Fiber Craft Workstation' })).toBeVisible(); await expect(page.getByTestId('active-round-progress')).toHaveText('0 of 6 stitches worked');
    const undo = page.getByRole('button', { name: 'Undo' }); const redo = page.getByRole('button', { name: 'Redo' }); await expect(undo).toBeDisabled(); await expect(redo).toBeDisabled();
    await page.locator('#fiber-stitch-symbol').selectOption('sc-dc'); await page.getByRole('button', { name: 'Place next stitch' }).click(); await expect(page.getByTestId('active-round-progress')).toHaveText('1 of 6 stitches worked'); await expect(page.getByTestId('crochet-round-canvas')).toHaveAttribute('data-symbol-rendering','vector'); await expect(page.getByTestId('written-pattern')).toContainText('1 sc [Primary]'); await expect(page.getByTestId('chart-description')).toContainText('Round 1: 6 positions, 1 worked, 5 unworked.');
    await page.locator('#fiber-display-theme').selectOption('high-contrast'); await expect(page.locator('.fiber-craft-workspace')).toHaveAttribute('data-fiber-theme','high-contrast'); await page.emulateMedia({ media: 'print' }); await expect(page.getByTestId('crochet-round-canvas')).toHaveCSS('filter','grayscale(1) contrast(1.8)'); await page.emulateMedia({ media: 'screen' }); await page.locator('#fiber-display-theme').selectOption('light');
    await undo.click(); await expect(page.getByTestId('active-round-progress')).toHaveText('0 of 6 stitches worked'); await redo.click(); await expect(page.getByTestId('active-round-progress')).toHaveText('1 of 6 stitches worked');
    await page.getByRole('button', { name: 'Mark round complete' }).click(); await page.getByLabel('Yarn weight').selectOption('4'); await page.getByRole('button', { name: 'Use these project defaults' }).click();
    await page.locator('#fiber-gauge-stitches').fill('20'); await page.locator('#fiber-gauge-rows').fill('28'); await page.locator('#fiber-gauge-span').fill('4'); await page.getByRole('button', { name: 'Save measured gauge' }).click(); await page.locator('#fiber-project-level').selectOption('Intermediate'); await page.locator('#fiber-technique-tags').fill('amigurumi, shaping'); await page.getByRole('button', { name: 'Save pattern details' }).click();
    await page.locator('#fiber-png-scale').selectOption('4'); const [roundPng] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: 'Export PNG' }).click()]); await expect(inspectPngDownload(roundPng)).resolves.toEqual({ width:3840,height:2880 });
    const [patternPdf] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: 'Export pattern PDF' }).click()]); await inspectPdfDownload(patternPdf);
    const [socialPreview] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: 'Export social preview' }).click()]); await expect(inspectPngDownload(socialPreview)).resolves.toEqual({ width:1200,height:630 });
    await page.getByLabel('Chart mode').selectOption('grid'); await page.getByRole('button', { name: 'Row 1, column 1, open' }).click(); await expect(page.getByTestId('c2c-summary')).toContainText('1 filled block'); await page.getByRole('button', { name: 'Mark row complete' }).click();
    const [projectDownload] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: 'Save .craftproj' }).click()]); const projectPath = await projectDownload.path(); expect(projectPath).not.toBeNull(); await page.getByRole('button', { name: /Row 1, column 1, filled/ }).click(); await page.getByLabel('Open project file').setInputFiles(projectPath!); await expect(page.getByRole('button', { name: /Row 1, column 1, filled/ })).toBeVisible();
    await expect(page.locator('p.fiber-craft-status')).toContainText('Saved locally', { timeout:3_000 }); await page.reload(); const restore = page.getByRole('button', { name:'Restore last session' }); await expect(restore).toBeVisible(); await restore.click(); await expect(page.getByLabel('Chart mode')).toHaveValue('grid');
  });

  test('authors and restores a counted-thread chart with a live symbol key', async ({ page }) => {
    await page.goto('./#/fiber-craft-workstation'); await expect(page.getByRole('heading', { name:'Fiber Craft Workstation' })).toBeVisible(); await page.getByLabel('Workspace').selectOption('counted-thread');
    await expect(page.getByRole('heading', { name:'Counted-thread grid' })).toBeVisible(); await expect(page.getByTestId('counted-thread-summary')).toHaveText('0 stitches · 0 knots · 0 backstitches');
    await page.getByRole('gridcell', { name:'Row 1, column 1, empty' }).click(); await expect(page.getByRole('gridcell', { name:/Row 1, column 1, Full cross/ })).toBeVisible(); await expect(page.getByTestId('counted-thread-legend')).toContainText('Primary'); await expect(page.getByTestId('counted-thread-legend')).toContainText('1 used');
    await page.locator('#fiber-counted-stitch').selectOption('quarter-ne'); await page.locator('#fiber-counted-color').selectOption('accent'); await page.getByRole('gridcell', { name:'Row 1, column 2, empty' }).click(); await expect(page.getByTestId('counted-thread-legend')).toContainText('Accent');
    await page.getByRole('button', { name:'Add French knot' }).click(); await page.getByRole('button', { name:'Add backstitch' }).click(); await expect(page.getByTestId('counted-thread-summary')).toHaveText('2 stitches · 1 knots · 1 backstitches');
    const [projectDownload] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name:'Save .craftproj' }).click()]); expect(projectDownload.suggestedFilename()).toBe('counted-thread-chart.craftproj'); const projectPath = await projectDownload.path(); expect(projectPath).not.toBeNull();
    await page.getByRole('gridcell', { name:/Row 1, column 1, Full cross/ }).click(); await page.getByLabel('Open project file').setInputFiles(projectPath!); await expect(page.getByRole('gridcell', { name:/Row 1, column 1, Full cross/ })).toBeVisible(); await expect(page.getByTestId('counted-thread-summary')).toHaveText('2 stitches · 1 knots · 1 backstitches');
    await expect(page.locator('p.fiber-craft-status')).toContainText('Saved locally', { timeout:3_000 }); await page.reload(); const restore = page.getByRole('button', { name:'Restore last session' }); await expect(restore).toBeVisible(); await restore.click(); await expect(page.getByLabel('Workspace')).toHaveValue('counted-thread'); await expect(page.getByTestId('counted-thread-legend')).toContainText('Accent');
  });

  test('reopens the Fiber workspace while offline after the PWA is installed', async ({ page, context }) => { await page.goto('./#/fiber-craft-workstation'); await expect(page.getByRole('heading', { name:'Fiber Craft Workstation' })).toBeVisible(); await expect(page.evaluate(() => 'serviceWorker' in navigator)).resolves.toBe(true); await page.evaluate(async () => { const registration = await navigator.serviceWorker.ready; if (!registration.active) throw new Error('Service worker did not activate.'); }); await page.reload(); await expect.poll(() => page.evaluate(() => Boolean(navigator.serviceWorker.controller))).toBe(true); await context.setOffline(true); try { await page.reload({ waitUntil:'domcontentloaded' }); await expect(page.getByRole('heading', { name:'Fiber Craft Workstation' })).toBeVisible(); await expect(page.getByRole('button', { name:'Save .craftproj' })).toBeVisible(); } finally { await context.setOffline(false); } });
});
