import { useMemo, useState } from 'react';
import { getCronRuns, projectRunToZones } from './cron-engine';
const DEFAULT_ZONES=['UTC','America/New_York','America/Chicago','Europe/London','Asia/Kolkata'];
export default function CronWorkspace(){const[expression,setExpression]=useState('0 9 * * 1-5');const[sourceZone,setSourceZone]=useState('UTC');const[zones,setZones]=useState(DEFAULT_ZONES.join('\n'));const[status,setStatus]=useState('Showing the next scheduled runs.');
 const zoneList=useMemo(()=>zones.split(/\r?\n|,/).map(v=>v.trim()).filter(Boolean),[zones]);let runs:Date[]=[];let error='';try{runs=getCronRuns(expression,{count:30,startDate:new Date(),timeZone:sourceZone})}catch(e){error=e instanceof Error?e.message:'Invalid cron expression'}
 const hourCounts=useMemo(()=>{const counts=new Map<number,number>();for(const run of runs){const hour=Number(new Intl.DateTimeFormat('en-US',{timeZone:sourceZone,hour:'2-digit',hourCycle:'h23'}).format(run));counts.set(hour,(counts.get(hour)||0)+1)}return counts},[runs,sourceZone]);
 return <><div className="workspace-header"><div><h2>Global cron matrix</h2><p>Each row is one instant projected into every selected timezone.</p></div></div><div className="workspace-body"><div className="workspace-grid"><div className="field"><label htmlFor="cron">Cron expression</label><input id="cron" type="text" value={expression} onChange={e=>{setExpression(e.target.value);setStatus('Schedule updated.')}} spellCheck={false}/></div><div className="field"><label htmlFor="source-zone">Source timezone</label><input id="source-zone" type="text" value={sourceZone} onChange={e=>setSourceZone(e.target.value)} list="common-zones"/><datalist id="common-zones">{DEFAULT_ZONES.map(z=><option key={z} value={z}/>)}</datalist></div></div><div className="field" style={{marginTop:16}}><label htmlFor="zones">Comparison timezones</label><textarea id="zones" value={zones} onChange={e=>setZones(e.target.value)} style={{minHeight:100}}/><small>One IANA timezone per line.</small></div>
 {error?<div className="status-line error" role="status">{error}</div>:<><div className="status-line good" role="status">{status} {runs.length} upcoming runs calculated locally.</div><div className="metric-row" aria-label="24-hour run distribution">{Array.from({length:24},(_,hour)=><div className="metric" key={hour}><span>{String(hour).padStart(2,'0')}:00</span><strong>{hourCounts.get(hour)||0}</strong></div>)}</div><div className="result-table-wrap"><table><thead><tr><th scope="col">Run</th>{zoneList.map(zone=><th scope="col" key={zone}>{zone}</th>)}</tr></thead><tbody>{runs.map((run,index)=>{const projected=projectRunToZones(run,zoneList);return <tr key={run.toISOString()}><td>{index+1}</td>{zoneList.map(zone=><td key={zone}>{projected[zone]}</td>)}</tr>})}</tbody></table></div></>}
 </div></>}
