import { useMemo, useState } from 'react';
import { getCronRuns, isValidTimeZone, partitionTimeZones, projectRunToZones, runHourInZone } from './cron-engine';
const DEFAULT_ZONES=['UTC','America/New_York','America/Chicago','Europe/London','Asia/Kolkata'];
export default function CronWorkspace(){const[expression,setExpression]=useState('0 9 * * 1-5');const[sourceZone,setSourceZone]=useState('UTC');const[zones,setZones]=useState(DEFAULT_ZONES.join('\n'));const[runCount,setRunCount]=useState(30);const[status,setStatus]=useState('Showing the next scheduled runs.');
 const requestedZones=useMemo(()=>zones.split(/\r?\n|,/).map(v=>v.trim()).filter(Boolean),[zones]);
 // Timezones arrive as free text, so both the source zone and the comparison
 // list are validated before any Intl call. Previously an unrecognized IANA
 // name reached Intl.DateTimeFormat during render and the resulting RangeError
 // unmounted the workspace instead of reporting the bad zone.
 const {valid:zoneList,invalid:invalidZones}=useMemo(()=>partitionTimeZones(requestedZones),[requestedZones]);
 const sourceZoneValid=useMemo(()=>isValidTimeZone(sourceZone),[sourceZone]);
 let runs:Date[]=[];let error='';
 if(!sourceZoneValid){error=`"${sourceZone}" is not a timezone this browser recognizes. Use an IANA name such as UTC or Europe/London.`}
 else{try{runs=getCronRuns(expression,{count:runCount,startDate:new Date(),timeZone:sourceZone})}catch(e){error=e instanceof Error?e.message:'Invalid cron expression'}}
 const hourCounts=useMemo(()=>{const counts=new Map<number,number>();for(const run of runs){const hour=runHourInZone(run,sourceZone);if(hour===null)continue;counts.set(hour,(counts.get(hour)||0)+1)}return counts},[runs,sourceZone]);
 return <><div className="workspace-header"><div><h2>Global cron matrix</h2><p>Each row is one instant projected into every selected timezone.</p></div></div><div className="workspace-body"><div className="workspace-grid"><div className="field"><label htmlFor="cron">Cron expression</label><input id="cron" type="text" value={expression} onChange={e=>{setExpression(e.target.value);setStatus('Schedule updated.')}} spellCheck={false}/></div><div className="field"><label htmlFor="run-count">Runs to project</label><input id="run-count" type="number" min="1" max="200" value={runCount} onChange={e=>setRunCount(Math.max(1,Math.min(200,Number(e.target.value)||1)))}/><small>How far ahead to calculate, up to 200.</small></div><div className="field"><label htmlFor="source-zone">Source timezone</label><input id="source-zone" type="text" value={sourceZone} onChange={e=>setSourceZone(e.target.value)} list="common-zones"/><datalist id="common-zones">{DEFAULT_ZONES.map(z=><option key={z} value={z}/>)}</datalist></div></div><div className="field" style={{marginTop:16}}><label htmlFor="zones">Comparison timezones</label><textarea id="zones" value={zones} onChange={e=>setZones(e.target.value)} style={{minHeight:100}}/><small>One IANA timezone per line.</small>{invalidZones.length>0?<small className="cron-invalid-zones" data-testid="invalid-zones">Not recognized by this browser, so {invalidZones.length===1?'it was':'they were'} left out: {invalidZones.join(', ')}</small>:null}</div>
 {error?<div className="status-line error" role="status">{error}</div>:<><div className="status-line good" role="status">{status} {runs.length} upcoming runs calculated locally.</div><div className="metric-row" aria-label="24-hour run distribution">{Array.from({length:24},(_,hour)=><div className="metric" key={hour}><span>{String(hour).padStart(2,'0')}:00</span><strong>{hourCounts.get(hour)||0}</strong></div>)}</div><div className="result-table-wrap" role="region" aria-label="Upcoming runs by timezone" tabIndex={0}><table><thead><tr><th scope="col">Run</th>{zoneList.map(zone=><th scope="col" key={zone}>{zone}</th>)}</tr></thead><tbody>{runs.map((run,index)=>{const projected=projectRunToZones(run,zoneList);return <tr key={run.toISOString()}><td>{index+1}</td>{zoneList.map(zone=><td key={zone}>{projected[zone]}</td>)}</tr>})}</tbody></table></div></>}
 </div></>}
