import type { RegexFlavor } from './regex-types';
export interface RegexReferenceEntry { readonly id:string; readonly token:string; readonly label:string; readonly category:string; readonly description:string; readonly flavors:readonly RegexFlavor[]; }
const ALL:readonly RegexFlavor[]=['ecmascript','pcre','pcre2','python','go-re2','java','dotnet','rust','posix-ere','posix-bre','oniguruma'];
const MODERN:readonly RegexFlavor[]=['ecmascript','pcre','pcre2','python','go-re2','java','dotnet','rust','oniguruma'];
const e=(id:string,token:string,label:string,category:string,description:string,flavors:readonly RegexFlavor[]=ALL):RegexReferenceEntry=>({id,token,label,category,description,flavors});
export const REGEX_REFERENCE:readonly RegexReferenceEntry[]=[
 e('literal','a','Literal character','Basics','Matches the literal character.'),e('dot','.','Any character','Basics','Matches one character subject to newline rules.',MODERN),e('escape','\\.','Escaped literal','Basics','Escapes a metacharacter.'),e('start','^','Start anchor','Anchors','Asserts start of input or line.'),e('end','$','End anchor','Anchors','Asserts end of input or line.'),e('word-boundary','\\b','Word boundary','Anchors','Asserts a word transition.',MODERN),e('nonword-boundary','\\B','Non-word boundary','Anchors','Asserts a non-boundary.',MODERN),
 e('digit','\\d','Digit','Classes','Matches a digit.',MODERN),e('nondigit','\\D','Non-digit','Classes','Matches a non-digit.',MODERN),e('word','\\w','Word character','Classes','Matches a word character.',MODERN),e('nonword','\\W','Non-word character','Classes','Matches a non-word character.',MODERN),e('space','\\s','Whitespace','Classes','Matches whitespace.',MODERN),e('nonspace','\\S','Non-whitespace','Classes','Matches non-whitespace.',MODERN),e('class','[abc]','Character class','Classes','Matches one character from a set.'),e('neg-class','[^abc]','Negated class','Classes','Matches outside a set.'),e('range','[a-z]','Character range','Classes','Matches a range.'),e('posix-class','[[:alpha:]]','POSIX character class','Classes','Matches a POSIX named class.',['pcre','pcre2','go-re2','posix-ere','posix-bre','oniguruma']),e('unicode','\\p{L}','Unicode property','Classes','Matches a Unicode property.',['ecmascript','pcre','pcre2','java','dotnet','rust','oniguruma']),
 e('zero-one','a?','Zero or one','Quantifiers','Zero or one repetition.'),e('zero-more','a*','Zero or more','Quantifiers','Zero or more repetitions.'),e('one-more','a+','One or more','Quantifiers','One or more repetitions.'),e('exact','a{3}','Exact count','Quantifiers','Exact repetitions.'),e('range-count','a{2,5}','Count range','Quantifiers','Bounded repetitions.'),e('lazy','a+?','Lazy quantifier','Quantifiers','Prefers fewer repetitions.',MODERN),e('possessive','a++','Possessive quantifier','Quantifiers','Prevents quantifier backtracking.',['pcre','pcre2','python','java','oniguruma']),
 e('capture','(a)','Capture group','Groups','Groups and captures.'),e('noncapture','(?:a)','Non-capturing group','Groups','Groups without capture.',MODERN),e('named-js','(?<name>a)','Named capture','Groups','Named capture syntax.',['ecmascript','pcre','pcre2','java','dotnet','oniguruma']),e('named-python','(?P<name>a)','Python named capture','Groups','Python named capture syntax.',['python','pcre','pcre2','oniguruma']),e('atomic','(?>a+)','Atomic group','Groups','Prevents backtracking into the group.',['pcre','pcre2','python','java','dotnet','oniguruma']),e('branch-reset','(?|(a)|(b))','Branch reset group','Groups','Resets capture numbering across alternatives.',['pcre','pcre2']),
 e('alternation','a|b','Alternation','Logic','Matches either branch.'),e('lookahead','(?=a)','Positive lookahead','Lookaround','Asserts text ahead.',['ecmascript','pcre','pcre2','python','java','dotnet','oniguruma']),e('negative-lookahead','(?!a)','Negative lookahead','Lookaround','Rejects text ahead.',['ecmascript','pcre','pcre2','python','java','dotnet','oniguruma']),e('lookbehind','(?<=a)','Positive lookbehind','Lookaround','Asserts text behind.',['ecmascript','pcre','pcre2','python','java','dotnet','oniguruma']),e('negative-lookbehind','(?<!a)','Negative lookbehind','Lookaround','Rejects text behind.',['ecmascript','pcre','pcre2','python','java','dotnet','oniguruma']),
 e('backref','\\1','Numeric backreference','Backreferences','Repeats an earlier capture.',['ecmascript','pcre','pcre2','python','java','dotnet','posix-bre','oniguruma']),e('named-backref','\\k<name>','Named backreference','Backreferences','Repeats a named capture.',['ecmascript','pcre','pcre2','java','dotnet','oniguruma']),e('conditional','(?(1)yes|no)','Conditional','Logic','Conditional branch.',['pcre','pcre2','python','dotnet']),e('recursion','(?R)','Recursive pattern','Advanced','Recurses the pattern.',['pcre','pcre2']),
 e('inline-i','(?i:a)','Scoped case-insensitive flag','Flags','Scopes case-insensitive matching.',['pcre','pcre2','python','java','dotnet','oniguruma']),e('comment','(?# note )','Inline comment','Flags','Embeds a comment.',['pcre','pcre2','python','dotnet','oniguruma']),e('quote','\\Qtext\\E','Quoted literal','Escapes','Quotes literal text.',['pcre','pcre2','java','oniguruma']),e('newline','\\n','Newline escape','Escapes','Matches newline.',MODERN),e('tab','\\t','Tab escape','Escapes','Matches tab.',MODERN),e('hex','\\x41','Hex escape','Escapes','Hexadecimal character escape.',MODERN),e('unicode-escape','\\u0041','Unicode escape','Escapes','Unicode escape.',MODERN),
 e('replacement-1','$1','Replacement group 1','Substitution','Inserts group 1.',['ecmascript','java','dotnet']),e('replacement-name','${name}','Named replacement','Substitution','Inserts named capture.',['ecmascript','dotnet']),e('python-repl','\\g<1>','Python replacement group','Substitution','Python replacement reference.',['python']),e('pcre-verb','(*SKIP)','PCRE control verb','Advanced','Controls PCRE matching.',['pcre','pcre2']),e('pcre-keep','\\K','PCRE match reset','Advanced','Resets reported match start.',['pcre','pcre2']),e('dotnet-balance','(?<open>a)-(?<-open>b)','Balancing group','Advanced','.NET balancing groups.',['dotnet']),e('java-intersection','[a-z&&[^aeiou]]','Java class intersection','Classes','Java character-class intersection.',['java']),e('rust-set','[a-z&&[^aeiou]]','Rust class intersection','Classes','Rust character-class set operation.',['rust']),e('posix-bre-group','\\(ab\\)','POSIX BRE group','Groups','POSIX BRE capture syntax.',['posix-bre']),e('posix-ere-group','(ab)','POSIX ERE group','Groups','POSIX ERE grouping syntax.',['posix-ere'])
];
export const searchRegexReference=(query:string,flavor?:RegexFlavor):RegexReferenceEntry[]=>{const q=query.trim().toLowerCase();return REGEX_REFERENCE.filter((item)=>(!flavor||item.flavors.includes(flavor))&&(!q||`${item.token} ${item.label} ${item.category} ${item.description}`.toLowerCase().includes(q)));};
