import { useState } from 'react';
import { PDFDocument } from 'pdf-lib';
import { downloadBytes } from '../../lib/download';
import { splicePdfs } from './pdf-engine';
import { consumeFileInput } from '../../lib/file-input';

type PdfItem = { file: File; pageCount: number; pages: string; rotate: 0|90|180|270 };
function parsePages(value:string,max:number):number[]{if(!value.trim())return Array.from({length:max},(_,i)=>i+1);const pages:number[]=[];for(const token of value.split(',').map(v=>v.trim()).filter(Boolean)){if(token.includes('-')){const [a,b]=token.split('-').map(Number);if(!Number.isInteger(a)||!Number.isInteger(b)||a>b)throw new Error(`Invalid page range: ${token}`);for(let p=a;p<=b;p++)pages.push(p)}else{const p=Number(token);if(!Number.isInteger(p))throw new Error(`Invalid page: ${token}`);pages.push(p)}}return pages}
export default function PdfWorkspace(){const[items,setItems]=useState<PdfItem[]>([]);const[flatten,setFlatten]=useState(true);const[status,setStatus]=useState('Choose PDFs to merge, extract, reorder, rotate, or flatten.');const[busy,setBusy]=useState(false);
 async function load(list:FileList|null){if(!list)return;setBusy(true);try{const next:PdfItem[]=[];for(const file of Array.from(list)){const doc=await PDFDocument.load(await file.arrayBuffer(),{updateMetadata:false});next.push({file,pageCount:doc.getPageCount(),pages:'',rotate:0})}setItems(next);setStatus(`${next.length} PDF${next.length===1?'':'s'} ready. Reorder files and optionally select pages.`)}catch(error){setStatus(`Could not read PDF: ${error instanceof Error?error.message:'unknown error'}`)}finally{setBusy(false)}}
 function move(index:number,delta:number){setItems(current=>{const next=[...current];const target=index+delta;if(target<0||target>=next.length)return current;[next[index],next[target]]=[next[target],next[index]];return next})}
 function update(index:number,patch:Partial<PdfItem>){setItems(current=>current.map((item,i)=>i===index?{...item,...patch}:item))}
 // Names the output after the source when a single file was edited, so a
 // sanitized copy is identifiable rather than every export colliding on one
 // generic name.
 function outputName(){if(items.length===1){const base=items[0].file.name.replace(/\.pdf$/i,'');return `${base}.sanitized.pdf`}return `merged-${items.length}-documents.pdf`}
 function removeItem(index:number){setItems((current)=>current.filter((_,i)=>i!==index))}
 async function process(){setBusy(true);try{const selections=[];for(const item of items){selections.push({bytes:new Uint8Array(await item.file.arrayBuffer()),pages:parsePages(item.pages,item.pageCount),rotate:item.rotate,flatten})}const bytes=await splicePdfs(selections);downloadBytes(bytes,outputName(),'application/pdf');setStatus('Processed PDF created locally and sent to your downloads.')}catch(error){setStatus(`PDF processing failed: ${error instanceof Error?error.message:'unknown error'}`)}finally{setBusy(false)}}
 return <><div className="workspace-header"><div><h2>PDF splice and sanitizer</h2><p>File order becomes output order; page lists can reorder pages within each file.</p></div></div><div className="workspace-body"><div className="field"><label htmlFor="pdf-files">Choose PDF files</label><input id="pdf-files" type="file" accept="application/pdf,.pdf" multiple onChange={e=>consumeFileInput(e.target,()=>load(e.target.files))}/></div>
 {items.map((item,index)=><div className="notice" style={{marginTop:14}} key={`${item.file.name}-${index}`}><div className="workspace-grid three"><div><strong>{item.file.name}</strong><div className="help-text">{item.pageCount} pages</div></div><div className="field"><label htmlFor={`pages-${index}`}>Pages</label><input id={`pages-${index}`} type="text" placeholder="All, or 1,3,5-7" value={item.pages} onChange={e=>update(index,{pages:e.target.value})}/></div><div className="field"><label htmlFor={`rotate-${index}`}>Rotate output</label><select id={`rotate-${index}`} value={item.rotate} onChange={e=>update(index,{rotate:Number(e.target.value) as PdfItem['rotate']})}><option value="0">No rotation</option><option value="90">90°</option><option value="180">180°</option><option value="270">270°</option></select></div></div><div className="button-row"><button className="action-button secondary" type="button" disabled={index===0} onClick={()=>move(index,-1)}>Move up</button><button className="action-button secondary" type="button" disabled={index===items.length-1} onClick={()=>move(index,1)}>Move down</button><button className="action-button secondary" type="button" onClick={()=>removeItem(index)} data-testid={`pdf-remove-${index}`} aria-label={`Remove ${item.file.name} from the queue`}>Remove</button></div></div>)}
 <label style={{display:'flex',gap:10,alignItems:'center',marginTop:18}}><input type="checkbox" checked={flatten} onChange={e=>setFlatten(e.target.checked)}/> Flatten form fields before copying pages</label><div className="button-row"><button className="action-button" type="button" disabled={!items.length||busy} onClick={()=>void process()}>Process and download</button></div><div className="status-line" role="status">{busy?'Processing PDF bytes locally…':status}</div><p className="help-text">Common document metadata is removed from the output. Flattening makes current form appearances part of the page and removes editability.</p></div></>}
