import { useEffect, useMemo, useRef, useState } from 'react';
import { spanDepths, spanKey, type NormalizedSpan } from './otel-engine';

type Props={spans:NormalizedSpan[];selectedSpanKey?:string;criticalPath:string[];onSelect:(key:string)=>void};
type Hit={key:string;x:number;y:number;width:number;height:number;row:number};
function serviceColor(service:string){let hash=0;for(let index=0;index<service.length;index++)hash=(hash*31+service.charCodeAt(index))|0;return`hsl(${Math.abs(hash)%360} 58% 62%)`}
function maxEndOf(spans:NormalizedSpan[]){let max=1;for(const span of spans)max=Math.max(max,span.startMs+span.durationMs);return max}

export default function FlamegraphCanvas({spans,selectedSpanKey,criticalPath,onSelect}:Props){
 const ref=useRef<HTMLCanvasElement>(null),wrapRef=useRef<HTMLDivElement>(null),hits=useRef<Hit[]>([]),drag=useRef<{x:number;pan:number}|null>(null);const[width,setWidth]=useState(760),[zoom,setZoom]=useState(1),[panMs,setPanMs]=useState(0);const maxEnd=maxEndOf(spans);const critical=useMemo(()=>new Set(criticalPath),[criticalPath]);
 const layout=useMemo(()=>{const depths=spanDepths(spans),groups=new Map<number,NormalizedSpan[]>();for(const span of spans){const depth=depths.get(spanKey(span))??0;groups.set(depth,[...(groups.get(depth)??[]),span])}const rows=new Map<string,{row:number;depth:number;localLane:number}>();let rowOffset=0;for(const depth of[...groups.keys()].sort((a,b)=>a-b)){const laneEnds:number[]=[];for(const span of groups.get(depth)!.sort((a,b)=>a.startMs-b.startMs||a.durationMs-b.durationMs)){let lane=laneEnds.findIndex(end=>end<=span.startMs);if(lane<0){lane=laneEnds.length;laneEnds.push(0)}laneEnds[lane]=span.startMs+span.durationMs;rows.set(spanKey(span),{row:rowOffset+lane,depth,localLane:lane})}rowOffset+=Math.max(1,laneEnds.length)}return{rows,rowCount:Math.max(1,rowOffset)}},[spans]);
 const height=Math.max(180,44+layout.rowCount*34);
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;const observer=new ResizeObserver(([entry])=>setWidth(Math.max(320,Math.floor(entry.contentRect.width))));observer.observe(canvas);return()=>observer.disconnect()},[]);
 useEffect(()=>{setPanMs(current=>Math.max(0,Math.min(current,Math.max(0,maxEnd-maxEnd/zoom))))},[maxEnd,zoom]);
 useEffect(()=>{const selected=layout.rows.get(selectedSpanKey??'');const wrap=wrapRef.current;if(!selected||!wrap)return;const top=30+selected.row*34;if(top<wrap.scrollTop)wrap.scrollTop=Math.max(0,top-30);else if(top+34>wrap.scrollTop+wrap.clientHeight)wrap.scrollTop=top+34-wrap.clientHeight},[layout,selectedSpanKey]);
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;const dpr=window.devicePixelRatio||1;canvas.width=Math.floor(width*dpr);canvas.height=Math.floor(height*dpr);const ctx=canvas.getContext('2d');if(!ctx)return;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,width,height);const styles=getComputedStyle(document.documentElement),ink=styles.getPropertyValue('--ink').trim()||'#101820',muted=styles.getPropertyValue('--muted').trim()||'#59636e',line=styles.getPropertyValue('--line').trim()||'#d7dde3',signal=styles.getPropertyValue('--signal').trim()||'#205bd6',danger=styles.getPropertyValue('--danger').trim()||'#b3261e',surface=styles.getPropertyValue('--surface').trim()||'#fff';const left=72,right=12,top=30,plotWidth=Math.max(100,width-left-right),visible=maxEnd/zoom;ctx.font='10px ui-monospace, SFMono-Regular, Menlo, monospace';ctx.fillStyle=muted;ctx.strokeStyle=line;for(let tick=0;tick<=5;tick++){const x=left+plotWidth*tick/5,time=panMs+visible*tick/5;ctx.beginPath();ctx.moveTo(x,top-5);ctx.lineTo(x,height);ctx.stroke();const label=`${Math.round(time)} ms`;ctx.fillText(label,x-(tick===5?ctx.measureText(label).width:0),16)}hits.current=[];for(const span of spans){const key=spanKey(span),slot=layout.rows.get(key);if(!slot)continue;const x=left+(span.startMs-panMs)/visible*plotWidth,barWidth=Math.max(2,span.durationMs/visible*plotWidth),y=top+slot.row*34,barHeight=25;if(x+barWidth<left||x>width-right)continue;ctx.fillStyle=serviceColor(span.serviceName);ctx.fillRect(x,y,barWidth,barHeight);if(critical.has(key)){ctx.fillStyle=ink;ctx.font='12px sans-serif';ctx.fillText('◆',x+4,y+17)}if(span.error){ctx.fillStyle=danger;ctx.font='700 13px sans-serif';ctx.fillText('!',Math.min(x+barWidth-10,x+20),y+18)}if(key===selectedSpanKey){ctx.strokeStyle=signal;ctx.lineWidth=3;ctx.strokeRect(x-1,y-1,barWidth+2,barHeight+2);ctx.lineWidth=1}ctx.fillStyle=ink;ctx.font='600 10px ui-monospace, SFMono-Regular, Menlo, monospace';const prefix=critical.has(key)?'◆ ':span.error?'! ':'';if(barWidth>34){ctx.save();ctx.beginPath();ctx.rect(x+3,y,Math.max(0,barWidth-6),barHeight);ctx.clip();ctx.fillText(`${prefix}${span.name}`,x+6,y+17);ctx.restore()}hits.current.push({key,x,y,width:barWidth,height:barHeight,row:slot.row})}ctx.fillStyle=surface;ctx.fillRect(0,top,left-2,height-top);ctx.fillStyle=muted;ctx.font='10px ui-monospace, SFMono-Regular, Menlo, monospace';for(const[key,slot]of layout.rows){const span=spans.find(item=>spanKey(item)===key);if(span)ctx.fillText(`D${slot.depth}.${slot.localLane+1}`,8,top+slot.row*34+17)}},[critical,height,layout,maxEnd,panMs,selectedSpanKey,spans,width,zoom]);
 function selectAt(clientX:number,clientY:number){const canvas=ref.current;if(!canvas)return;const rect=canvas.getBoundingClientRect(),x=clientX-rect.left,y=clientY-rect.top;const hit=[...hits.current].reverse().find(item=>x>=item.x&&x<=item.x+item.width&&y>=item.y&&y<=item.y+item.height);if(hit)onSelect(hit.key)}
 function fit(){setZoom(1);setPanMs(0)}function onWheel(event:React.WheelEvent<HTMLCanvasElement>){event.preventDefault();const rect=event.currentTarget.getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(event.clientX-rect.left-72)/Math.max(1,rect.width-84))),oldVisible=maxEnd/zoom,nextZoom=Math.max(1,Math.min(40,zoom*(event.deltaY<0?1.25:.8))),nextVisible=maxEnd/nextZoom,anchor=panMs+ratio*oldVisible;setZoom(nextZoom);setPanMs(Math.max(0,Math.min(maxEnd-nextVisible,anchor-ratio*nextVisible)))}
 function onKeyDown(event:React.KeyboardEvent<HTMLCanvasElement>){const current=Math.max(0,spans.findIndex(span=>spanKey(span)===selectedSpanKey));if(event.key==='ArrowDown'){event.preventDefault();onSelect(spanKey(spans[Math.min(spans.length-1,current+1)]))}if(event.key==='ArrowUp'){event.preventDefault();onSelect(spanKey(spans[Math.max(0,current-1)]))}if(event.key==='+'||event.key==='='){event.preventDefault();setZoom(value=>Math.min(40,value*1.25))}if(event.key==='-'){event.preventDefault();setZoom(value=>Math.max(1,value*.8))}if(event.key==='Home'){event.preventDefault();fit()}}
 return <div style={{marginTop:18}}><div className="button-row"><button className="action-button secondary" type="button" onClick={fit}>Fit timeline</button><button className="action-button secondary" type="button" onClick={()=>setZoom(value=>Math.min(40,value*1.25))}>Zoom in</button><button className="action-button secondary" type="button" onClick={()=>setZoom(value=>Math.max(1,value*.8))}>Zoom out</button></div><div ref={wrapRef} role="region" aria-label="Scrollable trace flamegraph" tabIndex={0} style={{border:'1px solid var(--line)',borderRadius:'var(--radius-sm)',overflow:'auto',maxHeight:520}}><canvas ref={ref} tabIndex={0} aria-label={`Trace flamegraph with ${spans.length} spans in ${layout.rowCount} non-overlapping lanes.`} style={{width:'100%',height,display:'block',background:'var(--surface)',touchAction:'none'}} onClick={event=>selectAt(event.clientX,event.clientY)} onWheel={onWheel} onKeyDown={onKeyDown} onPointerDown={event=>{drag.current={x:event.clientX,pan:panMs};event.currentTarget.setPointerCapture(event.pointerId)}} onPointerMove={event=>{if(!drag.current)return;const visible=maxEnd/zoom,dx=event.clientX-drag.current.x;setPanMs(Math.max(0,Math.min(maxEnd-visible,drag.current.pan-dx/Math.max(1,width-84)*visible)))}} onPointerUp={()=>{drag.current=null}}/></div></div>;
}
