export type NormalizedSpan={traceId:string;spanId:string;parentSpanId?:string;name:string;serviceName:string;startMs:number;durationMs:number;error:boolean;attributes:Record<string,unknown>};
export type SpanTreeNode={span:NormalizedSpan;children:SpanTreeNode[]};
export const spanKey=(span:Pick<NormalizedSpan,'traceId'|'spanId'>)=>`${span.traceId}:${span.spanId}`;
export const parentKey=(span:NormalizedSpan)=>span.parentSpanId?`${span.traceId}:${span.parentSpanId}`:undefined;
function otelValue(value:any):unknown{if(!value||typeof value!=='object')return value;for(const key of['stringValue','intValue','doubleValue','boolValue','bytesValue'])if(key in value)return value[key];if(value.arrayValue?.values)return value.arrayValue.values.map(otelValue);if(value.kvlistValue?.values)return Object.fromEntries(value.kvlistValue.values.map((item:any)=>[item.key,otelValue(item.value)]));return value}
const attributes=(items:any[]=[])=>Object.fromEntries(items.map(item=>[String(item.key),otelValue(item.value)]));
function nanosToMs(value:string|number|bigint):number{const nanos=BigInt(value);return Number(nanos/1_000_000n)+Number(nanos%1_000_000n)/1_000_000}
function parseOtlp(input:any):NormalizedSpan[]{const spans:NormalizedSpan[]=[];for(const resourceSpan of input.resourceSpans??[]){const resourceAttributes=attributes(resourceSpan.resource?.attributes??[]);const serviceName=String(resourceAttributes['service.name']??'unknown-service');for(const group of resourceSpan.scopeSpans??resourceSpan.instrumentationLibrarySpans??[])for(const span of group.spans??[]){const attrs=attributes(span.attributes??[]);const start=nanosToMs(span.startTimeUnixNano??0),end=nanosToMs(span.endTimeUnixNano??span.startTimeUnixNano??0);spans.push({traceId:String(span.traceId??''),spanId:String(span.spanId??''),parentSpanId:span.parentSpanId?String(span.parentSpanId):undefined,name:String(span.name??'unnamed span'),serviceName,startMs:start,durationMs:Math.max(0,end-start),error:Number(span.status?.code??0)===2||'error.type'in attrs||'exception.message'in attrs||attrs.error===true,attributes:attrs})}}return spans}
function parseJaeger(input:any):NormalizedSpan[]{const spans:NormalizedSpan[]=[];for(const trace of input.data??[])for(const span of trace.spans??[]){const process=trace.processes?.[span.processID]??{};const tags=Object.fromEntries((span.tags??[]).map((tag:any)=>[String(tag.key),tag.value]));const childOf=(span.references??[]).find((reference:any)=>String(reference.refType??'').toUpperCase()==='CHILD_OF');const status=Number(tags['http.status_code']??tags['http.response.status_code']??0);spans.push({traceId:String(span.traceID??trace.traceID??''),spanId:String(span.spanID??''),parentSpanId:childOf?.spanID?String(childOf.spanID):undefined,name:String(span.operationName??'unnamed span'),serviceName:String(process.serviceName??'unknown-service'),startMs:Number(span.startTime??0)/1000,durationMs:Math.max(0,Number(span.duration??0)/1000),error:tags.error===true||status>=500,attributes:tags})}return spans}
export function parseTraceExport(input:any){const raw=Array.isArray(input?.resourceSpans)?parseOtlp(input):parseJaeger(input);const bases=new Map<string,number>();for(const span of raw){const current=bases.get(span.traceId);if(current===undefined||span.startMs<current)bases.set(span.traceId,span.startMs)}const spans=raw.map(span=>({...span,startMs:span.startMs-(bases.get(span.traceId)??0)})).sort((a,b)=>a.traceId.localeCompare(b.traceId)||a.startMs-b.startMs||a.spanId.localeCompare(b.spanId));return{spans,traces:[...new Set(spans.map(span=>span.traceId))]}}
export function buildSpanTree(spans:NormalizedSpan[]):SpanTreeNode[]{const nodes=new Map(spans.map(span=>[spanKey(span),{span,children:[] as SpanTreeNode[]}]));const roots:SpanTreeNode[]=[];for(const span of spans){const node=nodes.get(spanKey(span))!;const pk=parentKey(span),parent=pk?nodes.get(pk):undefined;if(parent&&parent!==node)parent.children.push(node);else roots.push(node)}const sort=(items:SpanTreeNode[])=>{items.sort((a,b)=>a.span.startMs-b.span.startMs||spanKey(a.span).localeCompare(spanKey(b.span)));items.forEach(item=>sort(item.children))};sort(roots);return roots}
function unionDuration(intervals:Array<[number,number]>):number{if(!intervals.length)return 0;const sorted=[...intervals].sort((a,b)=>a[0]-b[0]||a[1]-b[1]);let total=0,[start,end]=sorted[0];for(let i=1;i<sorted.length;i++){const[nextStart,nextEnd]=sorted[i];if(nextStart<=end)end=Math.max(end,nextEnd);else{total+=Math.max(0,end-start);start=nextStart;end=nextEnd}}return total+Math.max(0,end-start)}
export function exclusiveDuration(node:SpanTreeNode):number{const start=node.span.startMs,end=start+node.span.durationMs;const covered=node.children.map(child=>[Math.max(start,child.span.startMs),Math.min(end,child.span.startMs+child.span.durationMs)] as [number,number]).filter(([a,b])=>b>a);return Math.max(0,node.span.durationMs-unionDuration(covered))}
function longestPath(node:SpanTreeNode):{score:number;path:string[]}{const self=exclusiveDuration(node);if(!node.children.length)return{score:self,path:[spanKey(node.span)]};const best=node.children.map(longestPath).sort((a,b)=>b.score-a.score||a.path.join(':').localeCompare(b.path.join(':')))[0];return{score:self+best.score,path:[spanKey(node.span),...best.path]}}
export function computeCriticalPath(spans:NormalizedSpan[]):string[]{if(!spans.length)return[];const traces=new Set(spans.map(span=>span.traceId));if(traces.size>1){let best:{score:number;path:string[]}|undefined;for(const traceId of traces){const roots=buildSpanTree(spans.filter(span=>span.traceId===traceId));const candidate=roots.map(longestPath).sort((a,b)=>b.score-a.score)[0];if(candidate&&(!best||candidate.score>best.score))best=candidate}return best?.path??[]}const roots=buildSpanTree(spans);return roots.length?roots.map(longestPath).sort((a,b)=>b.score-a.score||a.path.join(':').localeCompare(b.path.join(':')))[0].path:[]}
export function spanDepths(spans:NormalizedSpan[]):Map<string,number>{const byKey=new Map(spans.map(span=>[spanKey(span),span]));const cache=new Map<string,number>();const depth=(span:NormalizedSpan,seen=new Set<string>()):number=>{const key=spanKey(span);if(cache.has(key))return cache.get(key)!;const pk=parentKey(span);if(!pk||seen.has(key))return 0;const parent=byKey.get(pk);if(!parent)return 0;seen.add(key);const value=depth(parent,seen)+1;cache.set(key,value);return value};return new Map(spans.map(span=>[spanKey(span),depth(span)]))}
