#!/usr/bin/env node
// pnpm docs:sync [--check]
// Regenerates the parts of the records that are derived from other files:
//  - docs/TOOL_INDEX.md tool table: one row per catalog tool (src/tools/*/*.meta.ts),
//    ordered by name; Name and Folder come from the meta file, Tracker and Standard from
//    the tool's standard documents. Hand-kept columns (Prefix, Spec, Plans, Other docs,
//    Task, Former names) are preserved; a new tool gets a row with them filled from its spec.
//  - .tasks/ITEMS.md: the task files in .tasks/items/, grouped by state.
// --check writes nothing and exits 1 if either file is out of date.
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { docsForTool, readHeader, standardDocs } from './tool-docs.mjs';
import { loadTools } from './tool-registry.mjs';

export const INDEX = 'docs/TOOL_INDEX.md';
export const ITEMS_DIR = '.tasks/items';
export const ITEMS_VIEW = '.tasks/ITEMS.md';
export const TASK_STATES = ['active', 'next', 'backlog', 'done', 'rejected'];
const COLUMNS = ['Slug', 'Name', 'Prefix', 'Folder', 'Spec', 'Tracker', 'Plans', 'Other docs', 'Task', 'Standard', 'Former names'];
const fromDocs = (path) => `../${path}`;
const link = (path, label = path.split('/').filter(Boolean).pop()) => `[${label}](${fromDocs(path)})`;

/** Slugs listed in the index's "Removed tools" table; never reused. */
export function removedSlugs(text = readFileSync(INDEX, 'utf8')) {
  const section = text.split('\n## Removed tools')[1] ?? '';
  return [...section.matchAll(/^\| `([a-z0-9-]+)` \|/gm)].map((match) => match[1]);
}

export function syncIndex(text, tools, docs) {
  const lines = text.split('\n');
  const header = lines.findIndex((line) => line.startsWith('| Slug | Name |'));
  if (header < 0) throw new Error(`${INDEX}: tool table header not found`);
  let end = header + 2;
  while (end < lines.length && lines[end].startsWith('| `')) end += 1;
  const rows = new Map(lines.slice(header + 2, end).map((line) => {
    const cells = line.split(' | ').map((cell) => cell.replace(/^\| ?| ?\|$/g, ''));
    return [cells[0].replace(/`/g, ''), cells];
  }));
  const removed = removedSlugs(text);
  const errors = [];
  for (const slug of rows.keys()) {
    if (!tools.some((tool) => tool.slug === slug)) errors.push(`${INDEX}: row "${slug}" has no catalog meta file; move it to "Removed tools" by hand`);
  }
  const next = tools.map((tool) => {
    if (removed.includes(tool.slug)) errors.push(`${tool.slug}: slug is listed under "Removed tools" and cannot be reused`);
    const { specs, trackers } = docsForTool(tool.slug, docs);
    const old = rows.get(tool.slug);
    const prefix = old?.[2] ?? (/Requirement prefix: `([A-Z0-9]+)`/.exec(specs[0]?.text ?? '')?.[1] || '—');
    const spec = old?.[4] ?? (specs.length ? `dedicated: ${specs.map((doc) => link(doc.path)).join(', ')}` : 'none: —');
    const tracker = trackers.length ? trackers.map((doc) => link(doc.path)).join(', ') : (old?.[5] ?? 'none');
    const standard = specs.length && trackers.length ? 'done' : old?.[9] && old[9] !== 'done' ? old[9] : 'pending';
    return [`\`${tool.slug}\``, tool.shortTitle, prefix, link(`src/tools/${tool.folder}/`, tool.folder), spec, tracker, old?.[6] ?? '—', old?.[7] ?? '—', old?.[8] ?? 'none', standard, old?.[10] ?? '—'];
  }).sort((a, b) => a[1].localeCompare(b[1], 'en', { sensitivity: 'base' }));
  if (lines[header] !== `| ${COLUMNS.join(' | ')} |`) errors.push(`${INDEX}: tool table columns changed; expected ${COLUMNS.join(', ')}`);
  const body = next.map((cells) => `| ${cells.join(' | ')} |`);
  return { text: [...lines.slice(0, header + 2), ...body, ...lines.slice(end)].join('\n'), errors };
}

/** Task files in .tasks/items/, as `{ file, header, title }`. */
export function readItems(root = process.cwd()) {
  const dir = `${root}/${ITEMS_DIR}`;
  if (!existsSync(dir)) return [];
  return readdirSync(dir).filter((file) => file.endsWith('.md')).sort().map((file) => {
    const text = readFileSync(`${dir}/${file}`, 'utf8');
    return { file, header: readHeader(text) ?? {}, title: /^# (.+)$/m.exec(text)?.[1] ?? file };
  });
}

export function renderItems(items) {
  const errors = [];
  const out = ['---', 'doc: task-view', '---', '', '# Task items', '', `Generated by \`pnpm docs:sync\` from \`${ITEMS_DIR}/\`; do not edit. Each task is one file there; its \`state\` field is the source of truth. Older records: [IN_PROGRESS.md](IN_PROGRESS.md), [NEXT.md](NEXT.md), [BACKLOG.md](BACKLOG.md), [DONE.md](DONE.md), [REJECTED.md](REJECTED.md).`, ''];
  for (const state of TASK_STATES) {
    const mine = items.filter((item) => item.header.state === state);
    out.push(`## ${state}`, '');
    if (!mine.length) out.push('None.', '');
    else out.push('| Task | Tool | Kind | Branch | Updated | Title |', '| --- | --- | --- | --- | --- | --- |', ...mine.map(({ file, header, title }) => `| [${header.task}](items/${file}) | \`${header.tool}\` | ${header.kind} | \`${header.branch}\` | ${header.updated} | ${title} |`), '');
  }
  for (const { file, header } of items) {
    if (!TASK_STATES.includes(header.state)) errors.push(`${ITEMS_DIR}/${file}: state "${header.state}" is not one of ${TASK_STATES.join(', ')}`);
    if (`${header.task}.md` !== file) errors.push(`${ITEMS_DIR}/${file}: task field "${header.task}" does not match the file name`);
  }
  return { text: out.join('\n'), errors };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const check = process.argv.includes('--check');
  const tools = await loadTools();
  const index = syncIndex(readFileSync(INDEX, 'utf8'), tools, standardDocs());
  const items = renderItems(readItems());
  const errors = [...index.errors, ...items.errors];
  const stale = [];
  for (const [path, text] of [[INDEX, index.text], [ITEMS_VIEW, items.text]]) {
    const current = existsSync(path) ? readFileSync(path, 'utf8') : '';
    if (current === text) continue;
    stale.push(path);
    if (!check) writeFileSync(path, text);
  }
  for (const error of errors) console.error(`error: ${error}`);
  if (check && stale.length) console.error(`out of date: ${stale.join(', ')} (run pnpm docs:sync)`);
  else if (!check) console.log(stale.length ? `updated: ${stale.join(', ')}` : 'up to date');
  process.exit(errors.length || (check && stale.length) ? 1 : 0);
}
