import { lazy, Suspense, useEffect, useMemo, useState } from 'react';
import { AppChrome } from './components/AppChrome';
import { TOOL_BY_SLUG, TOOLS, type ToolSlug } from './catalog';
import { useWorkspace } from './lib/workspace-context';
const Workspaces = lazy(() => import('./tools/workspaces'));
function useHashRoute(){const [hash,setHash]=useState(()=>window.location.hash||'#/');useEffect(()=>{const onHash=()=>setHash(window.location.hash||'#/');window.addEventListener('hashchange',onHash);return()=>window.removeEventListener('hashchange',onHash)},[]);return hash}
function LandingPage(){const {state}=useWorkspace();const recent=useMemo(()=>state.recent.map((slug)=>TOOL_BY_SLUG.get(slug as ToolSlug)).filter(Boolean),[state.recent]);const favorites=useMemo(()=>new Set(state.favorites),[state.favorites]);return <div className="landing-page">
<section className="hero"><div className="hero-copy"><h1>Private tools. Serious work. Nothing uploaded.</h1><p>Focused browser utilities for files, data, media, hardware, and developer workflows—built to do the processing where the data already is.</p><a className="primary-action" href="#catalog">Browse the tools</a></div><div className="hero-instrument" aria-label="Local processing model"><div className="instrument-line"><span>Input</span><strong>Your device</strong></div><div className="instrument-path" aria-hidden="true"><i/><i/><i/><i/><i/></div><div className="instrument-line"><span>Processing</span><strong>Browser memory</strong></div><div className="instrument-line"><span>Output</span><strong>Direct download</strong></div><div className="instrument-state"><span className="privacy-pulse" aria-hidden="true"/> No upload step</div></div></section>
{recent.length>0?<section className="recent-strip" data-testid="recent-tools" aria-labelledby="recent-heading"><h2 id="recent-heading">Pick up where you left off</h2><div className="recent-links">{recent.map((tool)=>tool?<a key={tool.slug} href={`#/tools/${tool.slug}`}>{tool.shortTitle}</a>:null)}</div></section>:null}
<section className="catalog-section" id="catalog" aria-labelledby="catalog-heading"><div className="section-heading"><div><h2 id="catalog-heading">Local workbench</h2><p>{TOOLS.length} purpose-built suites. No account required.</p></div><span className="catalog-key">Files in → work here → files out</span></div><div className="tool-catalog" data-testid="tool-catalog">{TOOLS.map((tool)=><a className="tool-row" href={`#/tools/${tool.slug}`} key={tool.slug}><div className="tool-row-main"><div className="tool-title-line"><h3>{tool.shortTitle}</h3>{favorites.has(tool.slug)?<span className="favorite-tag">Saved</span>:null}</div><p>{tool.summary}</p></div><div className="tool-row-meta"><span>{tool.audience.split(' · ')[0]}</span><span aria-hidden="true">↗</span></div></a>)}</div></section></div>}
export function App(){const route=useHashRoute();const match=/^#\/tools\/([^/?#]+)/.exec(route);const tool=route==='#/floorplan-studio'?TOOL_BY_SLUG.get('floorplan-studio'):match?TOOL_BY_SLUG.get(match[1] as ToolSlug):undefined;return <AppChrome>{tool?<Suspense fallback={<div className="loading-surface" role="status">Opening {tool.shortTitle}…</div>}><Workspaces tool={tool}/></Suspense>:<LandingPage/>}</AppChrome>}
