export type ToolSlug =
  | 'exif-scrubber'
  | 'duckdb-workbench'
  | 'subtitle-drift'
  | 'hardware-packet-inspector'
  | 'fluid-type-matrix'
  | 'pdf-sanitizer'
  | 'cron-team-matrix'
  | 'midi-harmony-lab'
  | 'svg-sprite-compiler'
  | 'regex-log-structurer';

export interface ToolDefinition {
  slug: ToolSlug;
  shortTitle: string;
  title: string;
  audience: string;
  summary: string;
  privacy: string;
  accepts: string;
  outputs: string;
  steps: string[];
  hint: string;
}

export const TOOLS: ToolDefinition[] = [
  { slug:'exif-scrubber', shortTitle:'EXIF Scrubber', title:'Zero-Knowledge Media EXIF Scrubber & Geotag Redactor', audience:'Photographers · journalists · privacy teams', summary:'Inspect sensitive image metadata, remove it by re-rendering the pixels, and download a clean copy without uploading the source.', privacy:'Image bytes and metadata inspection stay in your browser. The sanitized image is generated on this device.', accepts:'JPEG, PNG, or WebP image files supported by your browser', outputs:'Sanitized image with a new non-destructive filename', steps:['Choose an image.','Review any location or device identifiers found.','Sanitize and download the clean copy.'], hint:'Re-encoding may change file size or image encoding details. Keep the original until you verify the sanitized copy.' },
  { slug:'duckdb-workbench', shortTitle:'DuckDB Workbench', title:'DuckDB-Wasm In-Browser Parquet & CSV SQL Query Workbench', audience:'Data analysts · BI developers · data engineers', summary:'Open local CSV or Parquet extracts, query them with DuckDB-Wasm, inspect result rows, and export query output.', privacy:'Your selected data files stay on this device. SQL executes inside a browser Web Worker using WebAssembly.', accepts:'CSV and Parquet files', outputs:'Interactive result table plus CSV or JSON export', steps:['Choose one or more local data files.','Write SQL using the file name in FROM.','Run the query and export only the result you need.'], hint:'For very large files, keep the query selective. Browser memory is finite even though the data never needs to leave your device.' },
  { slug:'subtitle-drift', shortTitle:'Subtitle Drift', title:'Linear Subtitle Time-Drift Corrector & Waveform Re-Aligner', audience:'Video editors · translators · creators', summary:'Correct both a fixed offset and gradual timing drift using two trusted synchronization anchors.', privacy:'Subtitle text is parsed and transformed locally in your browser. No captions are sent anywhere.', accepts:'SRT and WebVTT text', outputs:'Corrected SRT or VTT with preserved cue text', steps:['Load or paste subtitles.','Enter the source and correct time for an early cue.','Enter the source and correct time for a late cue, then export.'], hint:'Use anchors as far apart as practical. A wider anchor span makes frame-rate drift correction more reliable.' },
  { slug:'hardware-packet-inspector', shortTitle:'Packet Inspector', title:'Web Serial / Web Bluetooth Hardware Packet Inspector', audience:'IoT developers · embedded engineers · robotics makers', summary:'Inspect live byte streams, view ASCII and hex, transmit packets, and test parsing rules without installing a desktop terminal.', privacy:'Hardware traffic is handled by browser device APIs and displayed on this device. Simulator mode works without hardware access.', accepts:'Serial byte streams, hex packets, or simulator events', outputs:'Live packet stream and transmitted bytes', steps:['Connect a serial device when supported, or start the simulator.','Inspect incoming ASCII/hex frames.','Send validated hex packets back to the device.'], hint:'Web Serial is primarily available in Chromium-based browsers and requires a secure context. Unsupported browsers can still use simulator mode.' },
  { slug:'fluid-type-matrix', shortTitle:'Fluid Type Matrix', title:'Fluid Typography & Spacing Matrix Generator with Multi-Viewport Simulator', audience:'Frontend developers · product designers', summary:'Generate mathematically correct CSS clamp() scales and compare the same type treatment across common viewport widths.', privacy:'All scale math and previews run locally in the browser.', accepts:'Minimum/maximum values, viewport range, ratio, and scale steps', outputs:'CSS custom properties and synchronized viewport previews', steps:['Set the viewport and value endpoints.','Adjust the modular scale ratio and steps.','Copy the generated CSS after reviewing all viewport previews.'], hint:'Treat the simulator as a comparison surface, not a substitute for testing inside your actual layout and content.' },
  { slug:'pdf-sanitizer', shortTitle:'PDF Sanitizer', title:'Client-Side PDF Splice, Flatten, and Form Sanitizer', audience:'Remote workers · legal staff · administrative teams', summary:'Merge PDFs, flatten interactive form fields, remove common document metadata, and download the processed file locally.', privacy:'PDF bytes are read and rewritten in browser memory. Documents are not uploaded to a server.', accepts:'PDF documents', outputs:'Merged and/or flattened sanitized PDF', steps:['Choose one or more PDFs in the order you want them merged.','Choose whether to flatten and sanitize metadata.','Process and download the resulting PDF.'], hint:'Flattening is intentionally irreversible in the output. Keep the original if the form may need later edits.' },
  { slug:'cron-team-matrix', shortTitle:'Cron Team Matrix', title:'Multi-Timezone Cron Schedule & Global Team Matrix Visualizer', audience:'DevOps engineers · system administrators · distributed teams', summary:'Resolve upcoming cron runs in the source timezone and compare each instant across global team timezones.', privacy:'Cron parsing and timezone projection use local JavaScript libraries and browser Intl APIs.', accepts:'Cron expression, source timezone, and comparison timezones', outputs:'Upcoming run table and 24-hour distribution matrix', steps:['Enter the cron expression and source timezone.','Select the team timezones that matter.','Review upcoming runs before scheduling maintenance or deploys.'], hint:'Timezone projections account for DST through the parser and Intl APIs; still verify policy-sensitive maintenance windows with the target system.' },
  { slug:'midi-harmony-lab', shortTitle:'MIDI Harmony Lab', title:'Web Audio Harmonic Progression & Voice-Leading MIDI Lab', audience:'Music producers · beatmakers · theory students', summary:'Build chord progressions, audition browser-synth voicings, compare note movement, and export standard MIDI.', privacy:'Chord generation, playback, and MIDI encoding happen on this device.', accepts:'Chord roots, qualities, inversions, beat lengths, and tempo', outputs:'Playable progression and downloadable MIDI file', steps:['Build a progression from chord controls.','Audition voicings and adjust inversions.','Export the progression as a MIDI file for your DAW.'], hint:'Use inversions to reduce large jumps between neighboring chords; smoother note movement usually transfers better to arranged parts.' },
  { slug:'svg-sprite-compiler', shortTitle:'SVG Sprite Compiler', title:'SVG Sprite Sheet Compiler & Geometry Optimizer', audience:'Web performance engineers · frontend developers', summary:'Batch-optimize SVG files, normalize color to currentColor when desired, and compile deterministic symbol sprites.', privacy:'SVG source text is parsed, optimized, and combined locally in your browser.', accepts:'SVG files', outputs:'Optimized <symbol> sprite sheet and per-file size savings', steps:['Choose SVG files.','Choose whether fills/strokes should inherit currentColor.','Compile, review savings, and download the sprite.'], hint:'Review multicolor artwork before enabling currentColor normalization; that option is best for monochrome icon systems.' },
  { slug:'regex-log-structurer', shortTitle:'Log Structurer', title:'Local-First Regex Delimited Log Structurer & Schema Extractor', audience:'Site reliability engineers · backend developers', summary:'Turn proprietary log lines into structured rows with named regex capture groups and export the result without a cloud parser.', privacy:'Log text and regex processing remain entirely in your browser.', accepts:'Plain-text logs and a JavaScript regular expression with named capture groups', outputs:'Structured table plus JSON, CSV, or Markdown export', steps:['Paste or load log text.','Write a regex with named capture groups such as (?<level>...).','Inspect matched/unmatched lines and export the structured rows.'], hint:'Start with one representative line, verify the captures, then run against the full incident log to avoid silently misclassifying rows.' }
];
export const TOOL_BY_SLUG = new Map(TOOLS.map((tool) => [tool.slug, tool]));
