export type ToolSlug =
  | 'exif-scrubber'
  | 'duckdb-workbench'
  | 'subtitle-drift'
  | 'hardware-packet-inspector'
  | 'fluid-type-matrix'
  | 'pdf-sanitizer'
  | 'cron-team-matrix'
  | 'midi-harmony-lab'
  | 'svg-sprite-compiler'
  | 'regex-log-structurer'
  | 'har-sanitizer'
  | 'geojson-simplifier'
  | 'fuzzy-deduplicator'
  | 'otel-flamegraph'
  | 'apca-token-matrix'
  | 'convolution-room-profiler'
  | 'glsl-sandbox'
  | 'video-keyframe-slicer'
  | 'gltf-optimizer'
  | 'font-subsetter'
  | 'json-lattice'
  | 'floorplan-studio'
  | 'regex-matrix'
  | 'aethercast';

export interface ToolDefinition {
  slug: ToolSlug;
  shortTitle: string;
  title: string;
  audience: string;
  summary: string;
  privacy: string;
  accepts: string;
  outputs: string;
  steps: string[];
  hint: string;
}

export const TOOLS: ToolDefinition[] = [
  { slug:'exif-scrubber', shortTitle:'EXIF Scrubber', title:'Zero-Knowledge Media EXIF Scrubber & Geotag Redactor', audience:'Photographers · journalists · privacy teams', summary:'Inspect sensitive image metadata, remove it by re-rendering the pixels, and download a clean copy without uploading the source.', privacy:'Image bytes and metadata inspection stay in your browser. The sanitized image is generated on this device.', accepts:'JPEG, PNG, or WebP image files supported by your browser', outputs:'Sanitized image with a new non-destructive filename', steps:['Choose an image.','Review any location or device identifiers found.','Sanitize and download the clean copy.'], hint:'Re-encoding may change file size or image encoding details. Keep the original until you verify the sanitized copy.' },
  { slug:'duckdb-workbench', shortTitle:'DuckDB Workbench', title:'DuckDB-Wasm In-Browser Parquet & CSV SQL Query Workbench', audience:'Data analysts · BI developers · data engineers', summary:'Open local CSV or Parquet extracts, query them with DuckDB-Wasm, inspect result rows, and export query output.', privacy:'Your selected data files stay on this device. SQL executes inside a browser Web Worker using WebAssembly.', accepts:'CSV and Parquet files', outputs:'Interactive result table plus CSV or JSON export', steps:['Choose one or more local data files.','Write SQL using the file name in FROM.','Run the query and export only the result you need.'], hint:'For very large files, keep the query selective. Browser memory is finite even though the data never needs to leave your device.' },
  { slug:'subtitle-drift', shortTitle:'Subtitle Drift', title:'Linear Subtitle Time-Drift Corrector & Waveform Re-Aligner', audience:'Video editors · translators · creators', summary:'Correct both a fixed offset and gradual timing drift using two trusted synchronization anchors.', privacy:'Subtitle text is parsed and transformed locally in your browser. No captions are sent anywhere.', accepts:'SRT and WebVTT text', outputs:'Corrected SRT or VTT with preserved cue text', steps:['Load or paste subtitles.','Enter the source and correct time for an early cue.','Enter the source and correct time for a late cue, then export.'], hint:'Use anchors as far apart as practical. A wider anchor span makes frame-rate drift correction more reliable.' },
  { slug:'hardware-packet-inspector', shortTitle:'Packet Inspector', title:'Web Serial / Web Bluetooth Hardware Packet Inspector', audience:'IoT developers · embedded engineers · robotics makers', summary:'Inspect live byte streams, view ASCII and hex, transmit packets, and test parsing rules without installing a desktop terminal.', privacy:'Hardware traffic is handled by browser device APIs and displayed on this device. Simulator mode works without hardware access.', accepts:'Serial byte streams, hex packets, or simulator events', outputs:'Live packet stream and transmitted bytes', steps:['Connect a serial device when supported, or start the simulator.','Inspect incoming ASCII/hex frames.','Send validated hex packets back to the device.'], hint:'Web Serial is primarily available in Chromium-based browsers and requires a secure context. Unsupported browsers can still use simulator mode.' },
  { slug:'fluid-type-matrix', shortTitle:'Fluid Type Matrix', title:'Fluid Typography & Spacing Matrix Generator with Multi-Viewport Simulator', audience:'Frontend developers · product designers', summary:'Generate mathematically correct CSS clamp() scales and compare the same type treatment across common viewport widths.', privacy:'All scale math and previews run locally in the browser.', accepts:'Minimum/maximum values, viewport range, ratio, and scale steps', outputs:'CSS custom properties and synchronized viewport previews', steps:['Set the viewport and value endpoints.','Adjust the modular scale ratio and steps.','Copy the generated CSS after reviewing all viewport previews.'], hint:'Treat the simulator as a comparison surface, not a substitute for testing inside your actual layout and content.' },
  { slug:'pdf-sanitizer', shortTitle:'PDF Sanitizer', title:'Client-Side PDF Splice, Flatten, and Form Sanitizer', audience:'Remote workers · legal staff · administrative teams', summary:'Merge PDFs, flatten interactive form fields, remove common document metadata, and download the processed file locally.', privacy:'PDF bytes are read and rewritten in browser memory. Documents are not uploaded to a server.', accepts:'PDF documents', outputs:'Merged and/or flattened sanitized PDF', steps:['Choose one or more PDFs in the order you want them merged.','Choose whether to flatten and sanitize metadata.','Process and download the resulting PDF.'], hint:'Flattening is intentionally irreversible in the output. Keep the original if the form may need later edits.' },
  { slug:'cron-team-matrix', shortTitle:'Cron Team Matrix', title:'Multi-Timezone Cron Schedule & Global Team Matrix Visualizer', audience:'DevOps engineers · system administrators · distributed teams', summary:'Resolve upcoming cron runs in the source timezone and compare each instant across global team timezones.', privacy:'Cron parsing and timezone projection use local JavaScript libraries and browser Intl APIs.', accepts:'Cron expression, source timezone, and comparison timezones', outputs:'Upcoming run table and 24-hour distribution matrix', steps:['Enter the cron expression and source timezone.','Select the team timezones that matter.','Review upcoming runs before scheduling maintenance or deploys.'], hint:'Timezone projections account for DST through the parser and Intl APIs; still verify policy-sensitive maintenance windows with the target system.' },
  { slug:'midi-harmony-lab', shortTitle:'MIDI Harmony Lab', title:'Web Audio Harmonic Progression & Voice-Leading MIDI Lab', audience:'Music producers · beatmakers · theory students', summary:'Build chord progressions, audition browser-synth voicings, compare note movement, and export standard MIDI.', privacy:'Chord generation, playback, and MIDI encoding happen on this device.', accepts:'Chord roots, qualities, inversions, beat lengths, and tempo', outputs:'Playable progression and downloadable MIDI file', steps:['Build a progression from chord controls.','Audition voicings and adjust inversions.','Export the progression as a MIDI file for your DAW.'], hint:'Use inversions to reduce large jumps between neighboring chords; smoother note movement usually transfers better to arranged parts.' },
  { slug:'svg-sprite-compiler', shortTitle:'SVG Sprite Compiler', title:'SVG Sprite Sheet Compiler & Geometry Optimizer', audience:'Web performance engineers · frontend developers', summary:'Batch-optimize SVG files, normalize color to currentColor when desired, and compile deterministic symbol sprites.', privacy:'SVG source text is parsed, optimized, and combined locally in your browser.', accepts:'SVG files', outputs:'Optimized <symbol> sprite sheet and per-file size savings', steps:['Choose SVG files.','Choose whether fills/strokes should inherit currentColor.','Compile, review savings, and download the sprite.'], hint:'Review multicolor artwork before enabling currentColor normalization; that option is best for monochrome icon systems.' },

  { slug:'har-sanitizer', shortTitle:'HAR Sanitizer', title:'Local HAR Credential Sanitizer & Network Waterfall Inspector', audience:'Security engineers · web developers · support teams', summary:'Inventory likely credentials in HTTP Archive traffic, inspect request timing, and create a reviewed shareable HAR with selected values redacted, hashed, or masked.', privacy:'HAR traffic metadata is parsed, reviewed, transformed, and exported only in this browser. Nothing is uploaded for analysis.', accepts:'HTTP Archive (.har) JSON files', outputs:'Sanitized HAR plus local credential findings and request waterfall', steps:['Choose a HAR file and review the detected credential categories.','Inspect requests in the local waterfall and choose which categories to sanitize.','Choose redaction, SHA-256, or a custom mask and download the sanitized HAR.'], hint:'A SHA-256 value is a stable pseudonym, not encryption. Low-entropy secrets may still be guessable, so use redaction when a stable identifier is unnecessary.' },
  { slug:'geojson-simplifier', shortTitle:'GeoJSON Simplifier', title:'Topology-Preserving GeoJSON Precision & Simplification Workbench', audience:'GIS developers · map designers · data visualization teams', summary:'Round coordinate precision and reduce geometry detail while preserving shared topology, then compare local vector previews and export GeoJSON or TopoJSON.', privacy:'Geometry is parsed, simplified, previewed, and exported entirely in your browser without a remote map or upload service.', accepts:'GeoJSON Feature, FeatureCollection, or compatible geometry JSON', outputs:'Simplified GeoJSON or topology-preserving TopoJSON', steps:['Choose a GeoJSON file.','Set coordinate precision and the amount of geometry detail to retain.','Compare before/after metrics and vector previews, then download the selected format.'], hint:'Aggressive simplification can remove meaningful shape detail. Compare both vertex counts and the local preview before publishing the result.' },
  { slug:'fuzzy-deduplicator', shortTitle:'Fuzzy Deduplicator', title:'Local Fuzzy Record Deduplicator & Canonical Merge Workbench', audience:'Data operations · CRM administrators · research teams', summary:'Find likely duplicate rows with weighted lexical and phonetic matching, review each cluster, choose canonical values, and export a deterministic reconciled CSV.', privacy:'CSV/XLSX parsing, candidate blocking, similarity scoring, reconciliation, and export stay on this device.', accepts:'CSV and XLSX spreadsheets', outputs:'Reviewed deduplicated CSV with source rows left unchanged', steps:['Choose a CSV or XLSX file and select a sheet when needed.','Choose matching columns, weights, and confidence threshold, then find clusters.','Reconcile canonical values or dismiss false positives before exporting the deduplicated CSV.'], hint:'Fuzzy matches are candidates, not facts. Review lower-confidence clusters carefully before merging identity-sensitive records.' },
  { slug:'otel-flamegraph', shortTitle:'Trace Flamegraph', title:'OpenTelemetry & Jaeger Trace Flamegraph Explorer', audience:'Site reliability engineers · backend developers · platform teams', summary:'Normalize local OTLP or Jaeger trace exports, explore span latency and hierarchy, filter services/errors, and follow a clearly marked critical path.', privacy:'Trace IDs, attributes, timing, and errors are processed only inside your browser and are never sent to a telemetry service.', accepts:'OTLP JSON resource spans and Jaeger JSON trace exports', outputs:'Interactive local flamegraph, span details, filters, and critical-path analysis', steps:['Choose an OTLP or Jaeger JSON trace export.','Filter by service, error state, or minimum latency and navigate the flamegraph.','Select spans to inspect IDs, timing, hierarchy, and attributes while following ◆ critical-path markers.'], hint:'Critical-path highlighting is an analysis aid based on the imported span relationships and timing; incomplete or sampled traces may omit causal work.' },
  { slug:'apca-token-matrix', shortTitle:'APCA Token Matrix', title:'APCA / OKLCH Color Token Matrix & Contrast Workbench', audience:'Design-system teams · frontend developers · accessibility reviewers', summary:'Parse modern CSS color tokens, compare every directional foreground/background pairing with APCA Lc guidance and conventional WCAG 2 contrast, preview component pairings, and export CSS custom properties.', privacy:'Color parsing, matrix calculation, previews, and CSS export run entirely in this browser. No design tokens are uploaded.', accepts:'Hex, RGB, HSL, OKLCH, and other supported CSS color token lines', outputs:'Directional APCA/WCAG matrix, component preview, and CSS custom-property export', steps:['Paste or edit color tokens.','Choose an APCA guidance role and inspect the accessible table or compact visual matrix.','Review a component pairing, optional color-vision preview, then copy or download the CSS variables.'], hint:'APCA Lc is shown as perceptual guidance and is not presented as WCAG 2.x conformance. Use the separately reported WCAG ratio for current WCAG 2 contrast checks.' },
  { slug:'convolution-room-profiler', shortTitle:'Room Profiler', title:'Local Convolution Room Profiler & 24-Bit Offline Renderer', audience:'Audio engineers · producers · sound designers', summary:'Load dry audio and an impulse response, audition an equal-power dry/wet convolution graph with pre-delay and filters, inspect live spectrum energy, pause/resume playback, and render the same graph to 24-bit PCM WAV.', privacy:'Audio decoding, convolution, playback analysis, and offline rendering use browser Web Audio APIs on this device. Source audio is never uploaded.', accepts:'Browser-decodable audio plus a room/cabinet impulse response', outputs:'Live convolved audition and downloadable 24-bit PCM WAV render', steps:['Choose a dry source and impulse-response file.','Set wet mix, pre-delay, low cut, and high cut, then audition or pause/resume locally.','Render the configured graph with OfflineAudioContext and download the 24-bit WAV.'], hint:'Long sources and impulse responses require browser memory for decoded buffers and offline rendering. Keep originals and audition the render before replacing production assets.' },
  { slug:'glsl-sandbox', shortTitle:'GLSL Sandbox', title:'WebGL2 GLSL Live Sandbox & Standalone Shader Exporter', audience:'Creative developers · graphics engineers · technical artists', summary:'Edit a GLSL ES fragment shader with CodeMirror, compile it against WebGL2, inspect line-addressable diagnostics, drive resolution/time/pointer uniforms, bind up to two local textures, and export a zero-dependency HTML demo.', privacy:'Shader source, image textures, compilation, rendering, and HTML export remain in the browser. No source or texture bytes are uploaded.', accepts:'GLSL ES fragment source and up to two optional local image textures', outputs:'Live WebGL2 preview, compiler diagnostics, and standalone HTML export', steps:['Edit or paste fragment shader source in the local CodeMirror editor.','Review compile/link diagnostics while testing u_resolution, u_time, u_mouse, and optional texture uniforms.','Export the current shader and embedded local textures as a standalone HTML file.'], hint:'WebGL compiler messages can vary by browser and GPU driver. The standalone export targets WebGL2 and should be tested on the browsers/devices you intend to support.' },
  { slug:'video-keyframe-slicer', shortTitle:'Keyframe Video Slicer', title:'Lossless Keyframe Video Slicer & Encoded-Packet Remuxer', audience:'Video editors · creators · media engineers', summary:'Inspect verified video keyframes, request a trim range, see the exact packet-safe range before export, and copy compatible encoded audio/video packets into a new container without decoding or re-encoding.', privacy:'Container parsing, keyframe verification, packet copying, and remuxing run entirely in this browser. Video and audio bytes are never uploaded.', accepts:'Local MP4, MOV, or WebM video with a supported encoded video track', outputs:'Packet-copied MP4, MOV, or WebM slice using a compatible source codec/container combination', steps:['Choose a local video and let the browser enumerate verified keyframes.','Set requested start/end times and review the disclosed keyframe-snapped export boundaries.','Export the packet-safe slice; compatible encoded video/audio packets are remuxed without decode/re-encode.'], hint:'Lossless packet slicing cannot create arbitrary frame-accurate video cuts. Start/end boundaries may move to keyframes, and unsupported codec/container combinations are rejected rather than silently re-encoded.' },
  { slug:'gltf-optimizer', shortTitle:'GLB Optimizer', title:'glTF / GLB Geometry & Texture Optimizer with Orbit Comparison', audience:'3D web developers · technical artists · performance teams', summary:'Inspect a self-contained GLB, reduce geometry with topology-aware mesh simplification, locally resize supported textures, compare before/after scene statistics in an orbit viewport, and download a new optimized GLB.', privacy:'GLB parsing, geometry changes, texture conversion, Three.js preview, and export remain on this device. Model bytes and textures are never uploaded.', accepts:'Self-contained binary .glb models', outputs:'Optimized GLB plus before/after byte, mesh, vertex, triangle, and texture metrics', steps:['Choose a self-contained GLB and inspect the original scene/metrics.','Set a polygon target and maximum texture dimension, then optimize locally.','Toggle before/after and wireframe views, inspect the result, then download the new GLB.'], hint:'Polygon reduction is lossy below a 100% target. Browser texture decoding/WebP encoding is capability-dependent; unsupported texture conversions preserve the source texture instead of failing the model.' },
  { slug:'font-subsetter', shortTitle:'Font Subsetter', title:'OpenType Glyph Coverage, Unicode Subsetter & WOFF2 Exporter', audience:'Frontend developers · type designers · design-system teams', summary:'Inspect OpenType naming/metrics and cmap coverage, select Unicode presets or exact custom text, retain .notdef plus required glyphs, generate a new font locally, compress it to WOFF2, and export matching @font-face CSS.', privacy:'Font parsing, WOFF2 decompression/compression, glyph selection, reconstruction, and export run entirely in this browser. Font bytes are never uploaded.', accepts:'TTF, OTF, WOFF, and WOFF2 fonts supported by the local OpenType parser', outputs:'Locally generated WOFF2 subset and matching @font-face CSS snippet', steps:['Choose a font and review source metrics and searchable cmap-backed glyph coverage.','Select Unicode presets and/or paste the exact characters your product needs.','Build the subset, review size/glyph counts, then download the WOFF2 file and CSS snippet.'], hint:'Subsetting removes unselected character coverage and may not preserve every advanced shaping/table feature of complex fonts. Keep the original and test the subset with the languages and OpenType behaviors your product requires.' },
  { slug:'regex-log-structurer', shortTitle:'Log Structurer', title:'Local-First Regex Delimited Log Structurer & Schema Extractor', audience:'Site reliability engineers · backend developers', summary:'Turn proprietary log lines into structured rows with named regex capture groups and export the result without a cloud parser.', privacy:'Log text and regex processing remain entirely in your browser.', accepts:'Plain-text logs and a JavaScript regular expression with named capture groups', outputs:'Structured table plus JSON, CSV, or Markdown export', steps:['Paste or load log text.','Write a regex with named capture groups such as (?<level>...).','Inspect matched/unmatched lines and export the structured rows.'], hint:'Start with one representative line, verify the captures, then run against the full incident log to avoid silently misclassifying rows.' },
  { slug:'json-lattice', shortTitle:'JSON Lattice Studio', title:'JSON Lattice Studio — Local Structured Data Graph, Diff & Query Workbench', audience:'Developers · data engineers · security reviewers', summary:'Normalize JSON, YAML, TOML, XML, or CSV into a local canonical model, explore and edit it as a graph, diff structures, protect sensitive values, generate schemas, query with JSONPath or DuckDB, and export locally.', privacy:'Structured data, graph layout, privacy analysis, queries, edits, autosave, and exports stay inside this browser. No payload is uploaded.', accepts:'JSON, YAML, TOML, XML, and CSV text or local files', outputs:'Edited structured data, schemas, flattened CSV, SVG/PNG/JPEG graph exports, and protected JSON copies', steps:['Paste or open structured data and choose its source format.','Search, collapse, edit, diff, protect, inspect, and query the canonical graph locally.','Export the canonical data or reviewed graph and safe-copy artifacts without a server round-trip.'], hint:'Privacy Shield and foreign-key links are heuristic or convention-based aids. Review sensitive exports, and remember browser/Wasm memory is finite for very large documents.' },
  { slug:'floorplan-studio', shortTitle:'PlanCraft Studio', title:'PlanCraft Studio — Local Architectural Floor Plan & Clearance Workbench', audience:'Architects · interior designers · facilities teams · homeowners', summary:'Draft millimeter-accurate walls, rooms, hosted openings, furniture and MEP symbols with local snapping, clearance analysis, undo/redo, and scale-aware vector exports.', privacy:'Plan geometry, component placement, clearance analysis, autosave, and PDF/DXF/SVG/JSON export run locally in your browser. No project data is uploaded.', accepts:'Pointer, touch, keyboard, local JSON backups, and parametric drafting inputs', outputs:'Scaled PDF, DXF R12/R2000, layered SVG, and lossless JSON project backup', steps:['Draft walls and openings with grid, angle, and magnetic snapping.','Stage furniture/MEP components and review rooms, dimensions, and clearance warnings.','Export a local scale-aware PDF, DXF, SVG, or JSON backup.'], hint:'ADA and clearance indicators are planning aids, not code-compliance certification. Verify final drawings against the codes and standards that govern your project.' },
  { slug:'regex-matrix', shortTitle:'RegexMatrix Studio & Academy', title:'RegexMatrix Studio & Academy — Local Multi-Engine Regex Debugger & Learning Lab', audience:'Developers · security engineers · students · educators', summary:'Debug real ECMAScript, PCRE2, Oniguruma, and Python patterns, inspect matches and structure, assess ECMAScript ReDoS ambiguity, compare target-flavor compatibility, generate production snippets, and practice through a built-in local Academy.', privacy:'Patterns, test strings, PCRE2 and Oniguruma WebAssembly execution, Pyodide Python execution, diagnostics, lesson progress, saved state, and exports stay on this device. No account or backend is required.', accepts:'Regular-expression patterns, flags, local test text, assertion cases, and built-in Academy exercises', outputs:'Match/group diagnostics, structural explanations, compatibility reports, ReDoS analysis, code snippets, assertion JSON, SVG diagrams, and compressed share state', steps:['Choose an execution engine or compatibility target and enter a pattern plus test subject.','Run and inspect matches, captures, structure, safety, assertions, and generated target-language code.','Switch to Academy for deterministic lessons, then open any exercise directly in Studio when you need deeper diagnostics.'], hint:'ECMAScript, PCRE2, Oniguruma, and Python are the execution engines in this release; Oniguruma execution currently maps the g, i, and u flags, and Python runs on a Pyodide runtime served from this site that loads on first use. Legacy PCRE, Go/RE2, Java, .NET, Rust, and POSIX are explicitly labeled compatibility/code-generation targets until verified offline runtimes are shipped.' },
  { slug:'aethercast', shortTitle:'AetherCast', title:'AetherCast — Local Air Quality Index & Solar UV Exposure Workbench', audience:'Outdoor coaches · endurance athletes · respiratory/cardiac risk households · environmental researchers', summary:'Import an hourly air-quality and UV export, compute US EPA AQI, European EAQI, and WHO 2021 guideline comparisons, estimate Fitzpatrick sun-exposure limits, screen for wildfire/inversion anomalies, and plan outdoor activity windows entirely offline.', privacy:'The imported dataset, all AQI/EAQI/WHO/UV computation, anomaly screening, and PDF/CSV/PNG export run only in this browser. AetherCast never contacts a network service itself; you bring your own previously downloaded data file.', accepts:'An Open-Meteo Air Quality API JSON export, a mapped CSV of hourly pollutant/UV readings, or a previously exported AetherCast JSON file', outputs:'Interactive AQI/UV forecast chart, WHO guideline comparison, activity advisory, anomaly log, and PDF/CSV/PNG/JSON export', steps:['Import an hourly air-quality/UV export file.','Choose your index standard, Fitzpatrick skin type, and any vulnerability lens.','Scrub the chart, review the advisory and anomaly log, then export a brief or dataset.'], hint:'AQI/UV estimates and wildfire/inversion flags are local screening aids, not medical or regulatory guidance — verify with your local air-quality authority for health-critical decisions.' },
];
export const TOOL_BY_SLUG = new Map(TOOLS.map((tool) => [tool.slug, tool]));
