import { useRef, useState } from 'react';
import { downloadBytes } from '../../lib/download';
import { buildChord, buildMidiBytes, type ChordSpec } from './music-engine';
const START:ChordSpec[]=[{root:'C4',quality:'major',inversion:0,beats:4},{root:'F4',quality:'major',inversion:1,beats:4},{root:'G4',quality:'major',inversion:1,beats:4},{root:'C4',quality:'major',inversion:0,beats:4}];
export default function MusicWorkspace(){const[chords,setChords]=useState<ChordSpec[]>(START);const[bpm,setBpm]=useState(120);const[status,setStatus]=useState('Adjust inversions to reduce large jumps between neighboring voicings.');const audioRef=useRef<AudioContext|null>(null);
 function update(index:number,patch:Partial<ChordSpec>){setChords(current=>current.map((chord,i)=>i===index?{...chord,...patch}:chord))}
 async function play(){const context=audioRef.current??new AudioContext();audioRef.current=context;await context.resume();let time=context.currentTime+.05;for(const chord of chords){const seconds=(60/bpm)*(chord.beats??4);for(const midi of buildChord(chord)){const osc=context.createOscillator();const gain=context.createGain();osc.frequency.value=440*Math.pow(2,(midi-69)/12);osc.type='triangle';gain.gain.setValueAtTime(.0001,time);gain.gain.exponentialRampToValueAtTime(.055,time+.02);gain.gain.exponentialRampToValueAtTime(.0001,time+Math.max(.08,seconds-.03));osc.connect(gain).connect(context.destination);osc.start(time);osc.stop(time+seconds)}time+=seconds}setStatus('Progression is playing through the browser Web Audio engine.')}
 function exportMidi(){const bytes=buildMidiBytes(chords,bpm);downloadBytes(bytes,'inmotools-progression.mid','audio/midi');setStatus('Standard MIDI file created locally and sent to your downloads.')}
 return <><div className="workspace-header"><div><h2>Harmony and voice-leading lab</h2><p>Web Audio handles auditioning; MIDI export stays binary and local.</p></div></div><div className="workspace-body"><div className="field" style={{maxWidth:220}}><label htmlFor="bpm">Tempo (BPM)</label><input id="bpm" type="number" min="30" max="300" value={bpm} onChange={e=>setBpm(Number(e.target.value))}/></div><div className="workspace-grid" style={{marginTop:18}}>{chords.map((chord,index)=><div className="notice" key={index}><strong>Chord {index+1}</strong><div className="workspace-grid" style={{marginTop:10}}><div className="field"><label htmlFor={`root-${index}`}>Root</label><input id={`root-${index}`} type="text" value={chord.root} onChange={e=>update(index,{root:e.target.value})}/></div><div className="field"><label htmlFor={`quality-${index}`}>Quality</label><select id={`quality-${index}`} value={chord.quality} onChange={e=>update(index,{quality:e.target.value as ChordSpec['quality']})}><option value="major">Major</option><option value="minor">Minor</option><option value="diminished">Diminished</option><option value="sus2">Sus2</option><option value="sus4">Sus4</option></select></div><div className="field"><label htmlFor={`inv-${index}`}>Inversion</label><select id={`inv-${index}`} value={chord.inversion} onChange={e=>update(index,{inversion:Number(e.target.value)})}><option value="0">Root</option><option value="1">First</option><option value="2">Second</option></select></div><div className="field"><label htmlFor={`beats-${index}`}>Beats</label><input id={`beats-${index}`} type="number" min="1" max="16" value={chord.beats} onChange={e=>update(index,{beats:Number(e.target.value)})}/></div></div><div className="help-text">MIDI notes: {buildChord(chord).join(' · ')}</div></div>)}</div><div className="button-row"><button className="action-button" type="button" onClick={()=>void play()}>Play progression</button><button className="action-button secondary" type="button" onClick={exportMidi}>Export MIDI</button></div><div className="status-line" role="status">{status}</div></div></>}
