import { describe, expect, it } from 'vitest';
import { collectRequiredCodePoints, inspectFont, subsetToWoff2, unicodeRangeForCodePoints } from '../../src/tools/font/font-engine';

const TINY_TTF_BASE64='AAEAAAAKAIAAAwAgT1MvMkUhRCwAAAEoAAAAYGNtYXAADACVAAABlAAAADRnbHlmssEZlgAAAdAAAABMaGVhZC7goYoAAACsAAAANmhoZWEFKgIqAAAA5AAAACRobXR4BuoALQAAAYgAAAAMbG9jYQAZADMAAAHIAAAACG1heHAABQAGAAABCAAAACBuYW1lKwzfCgAAAhwAAAEscG9zdAApACUAAANIAAAAKAABAAAAAQAA6SrXUV8PPPUAAQPoAAAAAOa6LvcAAAAA5rou9wAyAAACJgK8AAAAAwACAAAAAAAAAAEAAAMg/zgAAAKKAAAAZAIIAAEAAAAAAAAAAAAAAAAAAAADAAEAAAADAAQAAQAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAwJOAZAABQAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAPz8/PwAAAEEAQgMg/zgAAAMgAMgAAAAAAAAAAAAAAAAAAAAgAAAB9AAAAooAFAJsABkAAAACAAAAAwAAABQAAwABAAAAFAAEACAAAAAEAAQAAQAAAEL//wAAAEH////AAAEAAAAAAAAADQAZACYAAQAyAAABwgK8AAMAADMhESEyAZD+cAK8AAABADIAAAImArwAAgAAMxMTMvr6Arz9RAABADIAAAH0ArwAAwAAMxEhETIBwgK8/UQAAAAACgB+AAEAAAAAAAEADAAAAAEAAAAAAAIABwAMAAEAAAAAAAMAEwATAAEAAAAAAAQAFAAmAAEAAAAAAAYAEwATAAMAAQQJAAEAGAA6AAMAAQQJAAIADgBSAAMAAQQJAAMAJgBgAAMAAQQJAAQAKACGAAMAAQQJAAYAJgBgSW5tbyBGaXh0dXJlUmVndWxhcklubW9GaXh0dXJlLVJlZ3VsYXJJbm1vIEZpeHR1cmUgUmVndWxhcgBJAG4AbQBvACAARgBpAHgAdAB1AHIAZQBSAGUAZwB1AGwAYQByAEkAbgBtAG8ARgBpAHgAdAB1AHIAZQAtAFIAZQBnAHUAbABhAHIASQBuAG0AbwAgAEYAaQB4AHQAdQByAGUAIABSAGUAZwB1AGwAYQByAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAACQAJQ==';
function decodeFixture(){const binary=atob(TINY_TTF_BASE64);return Uint8Array.from(binary,(character)=>character.charCodeAt(0)).buffer;}

describe('font subsetter engine',()=>{
 it('deduplicates and sorts Unicode code points from presets plus custom text',()=>{expect(collectRequiredCodePoints({presets:[],customText:'BAA😀B'})).toEqual([65,66,0x1f600]);});
 it('extracts source metrics, weight/style, cmap glyphs, and safety diagnostics',async()=>{const inspection=await inspectFont(decodeFixture(),'fixture.ttf');expect(inspection.familyName).toBe('Inmo Fixture');expect(inspection.styleName).toBe('Regular');expect(inspection.cssStyle).toBe('normal');expect(inspection.weight).toBeGreaterThan(0);expect(inspection.glyphs.some((glyph)=>glyph.codePoint===65&&glyph.name==='A')).toBe(true);expect(inspection.safeToSubset).toBe(true);});
 it('generates compact unicode-range descriptors',()=>{expect(unicodeRangeForCodePoints([65,66,67,70,0x1f600])).toBe('U+41-43, U+46, U+1F600');});
 it('retains notdef plus requested glyphs, reports missing coverage, and emits WOFF2 metadata',async()=>{const result=await subsetToWoff2(decodeFixture(),{presets:[],customText:'A😀'});expect(result.codePoints).toEqual([65]);expect(result.missingCodePoints).toEqual([0x1f600]);expect(result.glyphCount).toBe(2);expect(result.unicodeRange).toBe('U+41');expect(result.cssStyle).toBe('normal');expect(String.fromCharCode(...result.bytes.slice(0,4))).toBe('wOF2');});
});
