import { describe, expect, it } from 'vitest';
import { clampGltfOptions, classifyGltfExtensions, inspectGlb, optimizeGlb, readGlbJson } from '../../src/tools/gltf/gltf-engine';

function makeTriangleGlb(extra: Record<string, unknown> = {}): Uint8Array {
  const positions = new Float32Array([0,0,0,1,0,0,0,1,0]); const indices = new Uint16Array([0,1,2]); const binary = new Uint8Array(44); binary.set(new Uint8Array(positions.buffer),0); binary.set(new Uint8Array(indices.buffer),36);
  const json = JSON.stringify({ asset:{version:'2.0',generator:'InmoTools unit fixture'}, scene:0, scenes:[{nodes:[0]}], nodes:[{mesh:0,name:'Triangle'}], meshes:[{name:'TriangleMesh',primitives:[{attributes:{POSITION:0},indices:1}]}], accessors:[{bufferView:0,componentType:5126,count:3,type:'VEC3',min:[0,0,0],max:[1,1,0]},{bufferView:1,componentType:5123,count:3,type:'SCALAR',min:[0],max:[2]}], bufferViews:[{buffer:0,byteOffset:0,byteLength:36,target:34962},{buffer:0,byteOffset:36,byteLength:6,target:34963}], buffers:[{byteLength:44}], ...extra });
  const rawJson=new TextEncoder().encode(json),jsonLength=Math.ceil(rawJson.length/4)*4,totalLength=12+8+jsonLength+8+binary.length,output=new Uint8Array(totalLength),view=new DataView(output.buffer);view.setUint32(0,0x46546c67,true);view.setUint32(4,2,true);view.setUint32(8,totalLength,true);view.setUint32(12,jsonLength,true);view.setUint32(16,0x4e4f534a,true);output.fill(0x20,20,20+jsonLength);output.set(rawJson,20);const binHeader=20+jsonLength;view.setUint32(binHeader,binary.length,true);view.setUint32(binHeader+4,0x004e4942,true);output.set(binary,binHeader+8);return output;
}

describe('glTF optimizer engine',()=>{
 it('clamps lossy controls to supported bounds',()=>{expect(clampGltfOptions({targetRatio:4,maxTextureDimension:16})).toEqual({targetRatio:1,maxTextureDimension:64});expect(clampGltfOptions({targetRatio:-1,maxTextureDimension:99999})).toEqual({targetRatio:.05,maxTextureDimension:8192});});
 it('inspects original GLB bytes without invoking a transform or rewriting them',async()=>{const input=makeTriangleGlb();const before=input.slice();const inspection=await inspectGlb(input);expect(input).toEqual(before);expect(inspection.stats.meshes).toBe(1);expect(inspection.stats.triangles).toBe(1);expect(inspection.inputBytes).toBe(input.byteLength);expect(inspection.extensionReport.policy).toBe('registered-preservation');});
 it('blocks unknown optional extensions before a read/write cycle can silently discard their payload',async()=>{const input=makeTriangleGlb({extensionsUsed:['VENDOR_unknown_payload'],extensions:{VENDOR_unknown_payload:{importantId:'00123'}}});const inspection=await inspectGlb(input);expect(inspection.extensionReport.unsupported).toEqual(['VENDOR_unknown_payload']);expect(inspection.extensionReport.policy).toBe('blocked-unknown-extension');expect(inspection.transformBlockers.join(' ')).toMatch(/unknown|unregistered|preserv/i);expect(readGlbJson(input).extensions.VENDOR_unknown_payload.importantId).toBe('00123');await expect(optimizeGlb(input,{targetRatio:1,maxTextureDimension:1024})).rejects.toThrow(/VENDOR_unknown_payload|unregistered|preserv/i);});
 it('classifies registered Khronos extensions separately from unknown payloads',()=>{const report=classifyGltfExtensions(['KHR_materials_unlit','VENDOR_custom'],[]);expect(report.supported).toContain('KHR_materials_unlit');expect(report.unsupported).toContain('VENDOR_custom');});
 it('preflights Draco as unsupported rather than trying to transform undecodable geometry',async()=>{const input=makeTriangleGlb({extensionsUsed:['KHR_draco_mesh_compression'],extensionsRequired:['KHR_draco_mesh_compression']});const inspection=await inspectGlb(input);expect(inspection.transformBlockers.join(' ')).toMatch(/Draco decoder/i);await expect(optimizeGlb(input,{targetRatio:.5,maxTextureDimension:1024})).rejects.toThrow(/Draco decoder/i);});
 it('round-trips an uncompressed triangle while preserving cameras and source texture formats policy',async()=>{const input=makeTriangleGlb({cameras:[{type:'perspective',perspective:{yfov:.8,znear:.1}}]});const result=await optimizeGlb(input,{targetRatio:1,maxTextureDimension:1024});expect(new DataView(result.bytes.buffer,result.bytes.byteOffset,result.bytes.byteLength).getUint32(0,true)).toBe(0x46546c67);expect(result.before.meshes).toBe(1);expect(result.after.meshes).toBe(1);expect(result.before.triangles).toBe(1);expect(result.after.triangles).toBe(1);expect(result.report.preservedTextureFormats).toBe(true);expect(result.report.cameraCountPreserved).toBe(true);expect(result.report.animationCountPreserved).toBe(true);expect(result.report.extensionPreservation.unsupported).toEqual([]);});
 it('parses only a valid glTF 2.0 JSON chunk',()=>{expect(readGlbJson(makeTriangleGlb()).asset.version).toBe('2.0');expect(()=>readGlbJson(new Uint8Array(24))).toThrow(/GLB|glTF/i);});
});
