import { describe, expect, it } from 'vitest';
import { buildSpanTree, computeCriticalPath, exclusiveDuration, parseTraceExport, spanKey, type NormalizedSpan } from '../../src/tools/otel/otel-engine';

const otlp={resourceSpans:[{resource:{attributes:[{key:'service.name',value:{stringValue:'checkout-api'}}]},scopeSpans:[{spans:[{traceId:'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',spanId:'1111111111111111',name:'POST /checkout',startTimeUnixNano:'1788024000000000000',endTimeUnixNano:'1788024000100000000',attributes:[],status:{code:1}},{traceId:'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',spanId:'2222222222222222',parentSpanId:'1111111111111111',name:'charge card',startTimeUnixNano:'1788024000020000000',endTimeUnixNano:'1788024000090000000',attributes:[{key:'error.type',value:{stringValue:'payment_declined'}}],status:{code:2}}]}]}]};
const jaeger={data:[{traceID:'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',processes:{p1:{serviceName:'inventory-api',tags:[]}},spans:[{traceID:'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',spanID:'3333333333333333',operationName:'reserve stock',references:[],startTime:1788024000000000,duration:120000,processID:'p1',tags:[]}]}]};

describe('OpenTelemetry trace normalization',()=>{
 it('normalizes OTLP timing, hierarchy, and error state with compound identities',()=>{const trace=parseTraceExport(otlp);expect(trace.spans).toHaveLength(2);expect(trace.traces).toEqual(['aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa']);expect(trace.spans[0]).toMatchObject({startMs:0,durationMs:100,error:false});expect(trace.spans[1]).toMatchObject({parentSpanId:'1111111111111111',durationMs:70,error:true});const tree=buildSpanTree(trace.spans);expect(tree).toHaveLength(1);expect(spanKey(tree[0].children[0].span)).toBe('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:2222222222222222');expect(computeCriticalPath(trace.spans)).toEqual(['aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:1111111111111111','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:2222222222222222'])});
 it('accepts Jaeger JSON and safely handles an orphaned parent',()=>{const trace=parseTraceExport(jaeger);expect(trace.spans[0]).toMatchObject({serviceName:'inventory-api',durationMs:120});const orphan={...trace.spans[0],spanId:'4444444444444444',parentSpanId:'missing-parent'};expect(buildSpanTree([orphan])).toHaveLength(1)});
 it('does not collide when two traces reuse the same span ID',()=>{const spans:NormalizedSpan[]=[{traceId:'trace-a',spanId:'same',name:'a',serviceName:'svc',startMs:0,durationMs:10,error:false,attributes:{}},{traceId:'trace-b',spanId:'same',name:'b',serviceName:'svc',startMs:0,durationMs:20,error:false,attributes:{}}];const roots=buildSpanTree(spans);expect(roots).toHaveLength(2);expect(new Set(roots.map(root=>spanKey(root.span))).size).toBe(2)});
});

describe('critical path timing semantics',()=>{
 it('subtracts direct child coverage from parent self-time',()=>{const root:NormalizedSpan={traceId:'t',spanId:'root',name:'root',serviceName:'svc',startMs:0,durationMs:100,error:false,attributes:{}},child:NormalizedSpan={traceId:'t',spanId:'child',parentSpanId:'root',name:'child',serviceName:'svc',startMs:20,durationMs:70,error:false,attributes:{}};const tree=buildSpanTree([root,child]);expect(exclusiveDuration(tree[0])).toBe(30);expect(exclusiveDuration(tree[0].children[0])).toBe(70)});
 it('does not double-count nested inclusive durations when choosing a path',()=>{const spans:NormalizedSpan[]=[{traceId:'t',spanId:'root-a',name:'root a',serviceName:'svc',startMs:0,durationMs:100,error:false,attributes:{}},{traceId:'t',spanId:'child-a',parentSpanId:'root-a',name:'child a',serviceName:'svc',startMs:20,durationMs:70,error:false,attributes:{}},{traceId:'t',spanId:'root-b',name:'root b',serviceName:'svc',startMs:0,durationMs:120,error:false,attributes:{}}];expect(computeCriticalPath(spans)).toEqual(['t:root-b'])});
});
